### ISSUE TITLE
Tooltip is not firing on request to register

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1008]
Usually Disabled button wrapped with tooltip component shows the following message.

<img width="306" alt="Screenshot 2020-12-02 at 10 48 51" src="https://user-images.githubusercontent.com/2630/100863252-31c51f00-348c-11eb-8860-d66892a34d86.png">

However, tooltip does not appear for `request-register-button`

<img width="386" alt="Screenshot 2020-12-02 at 10 48 45" src="https://user-images.githubusercontent.com/2630/100863253-32f64c00-348c-11eb-878f-53a57bbb5d8e.png">

I did check that the button is wrapped with Tooltip component and it emits show/hide event.

```js
          ) : readOnly ? (
            <Tooltip
              text="<p>You are not connected to a web3 browser. Please connect to a web3 browser and try again</p>"
              position="top"
              border={true}
              offset={{ left: -30, top: 10 }}
            >
              {({ tooltipElement, showTooltip, hideTooltip }) => {
                return (
                  <Button
                    data-testid="request-register-button"
                    type="disabled"
                    onMouseOver={() => {
                      showTooltip()
                    }}
                    onMouseLeave={() => {
                      hideTooltip()
                    }}
                  >
                    {t('register.buttons.request')}
                  </Button>
                )
              }}
            </Tooltip>
```

I suspect it's more of css issue not rendering properly.

**Comment by LeonmanRolls** [comment]
No longer relevant due to redesign
