### ISSUE TITLE
Rearchitecture the Name Component to use multicall

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#1034]
Multicall can get all the records at once and reduce the amount of calls we make to the resolvers.

- UI will mandate multicall by calling supportsInterface or calling multicall with empty array. If it doesn't we will not let them edit
- Multicall will get all records in one call
- SupportsInterface multicall to get all the interfaces 'this' resolver supports and only shows those records

Likely to fix #1000

**Comment by makoto** [comment]
@jefflau don't we already support this? If so, please close
