### ISSUE TITLE
Adding ADA address doesn't work

### ISSUE THREAD

**Issue by abueide** [ensdomains/ens-app#1039]
**Describe the bug**
I'm trying to add an ada (cardano) address to my ens domain, but it turns red and doesn't let me add it. I'm pretty sure the address is valid since I'm clicking the copy button from the daedalus client and have verified they match manually.

Here is an example of an address I try to add but it doesn't let me: addr1qy5wyt323echwg7sk5q65pd349tgkcp2ldt9p5w4jzvq6t28m7ka29xpvhamrzml2qj7q8gq6z8gpvnkn9dx9awk5mqq9rxjn3

**To Reproduce**
Go to ens manager edit records, add new ada address and copy and paste an ada address into the field. It won't let you submit it.

**Expected behavior**
Allow me to add an ada address to my ens domain.

**Screenshots**
![image](https://user-images.githubusercontent.com/19354425/103146386-9da24c80-4705-11eb-873a-466f430780d5.png)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. chrome, safari] Chrome

**Comment by Ucodia** [comment]
I was able to reproduce this issue. It seems that the format definition for `ADA` is incorrect.
See current definition in `address-encoder` package: https://github.com/ensdomains/address-encoder/blob/master/src/index.ts#L1392

**Comment by makoto** [comment]
Fixed at https://github.com/ensdomains/ens-app/pull/1254
