### ISSUE TITLE
Multi-year registration broken during initial registration

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#1057]
I just tried registering bitcoinwhitepaper.eth for 5 years during the initial registration, but it only registered it for 1 year, and I was only charged for 1 year

https://etherscan.io/tx/0x2a803376c5295823a1d69dd65dbde76c9c543efd0b2828f0de08e5c5726915ba

**Comment by makoto** [comment]
I tried the same on ropsten but cannot replicate the issue. Can you also try on ropsten?
