### ISSUE TITLE
IPFS contenthash changes when saved

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1069]
**To Reproduce**

1. Go to any name you own
2. Set `ipfs://bafkreifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m` into content hash.
3. Click `save`

**Expected behavior**

it should show

`ipfs://baf[kr]eifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m`

but it shows

`ipfs://baf[yb]eifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m`

**Screenshots**
<img width="1639" alt="Screenshot 2021-02-02 at 18 10 12" src="https://user-images.githubusercontent.com/2630/106643673-f7f2c080-6581-11eb-9ab7-51d84f6f00fc.png">

Possible bug on ipfs encoding/decoding on client library

**Comment by lidel** [comment]
You can see the diff here:
- https://cid.ipfs.io/#bafkreifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m
- https://cid.ipfs.io/#bafybeifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m

The difference is in the multicodec: one is `raw` (0x55), other one is `dag-pb` (0x70)


I suspect somewhere in the code (either backend or frontend) you assume every CIDv1 is `dag-pb`, which is not true.  Only CIDv0 are all `dag-pb`. CIDv1 can have arbitrary codec.

**Comment by makoto** [comment]
Looks like it's happening when it encodes the text and decode back to check the format.

First it  encodes to convert `baf[kr]eifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m` to `0xe30101551220a61c8726a2cbdb52a60d1cc0e1b4b3c798839d437f31549219c623f847caf2e3` at https://github.com/ensdomains/ui/blob/master/src/utils/contents.js#L66

```
contentHash.encode('ipfs-ns', content);
```

And then decode `0xe30101551220a61c8726a2cbdb52a60d1cc0e1b4b3c798839d437f31549219c623f847caf2e3` to try to get original text`baf[yb]eifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m`

https://github.com/ensdomains/ui/blob/master/src/utils/contents.js#L19

` decoded = contentHash.helpers.cidV0ToV1Base32(decoded)`


and implementation is here https://github.com/ensdomains/content-hash/blob/master/src/helpers.js#L53

```
const cidV0ToV1Base32 = (ipfsHash) => {
	let cid = new CID(ipfsHash);
	if (cid.version === 0) {
		cid = cid.toV1();
	}
	return cid.toString('base32');
}
```

One question is that do you always get the same text if you encode and decode back again? If not, probably I need to change how to verify the contenthash

**Comment by makoto** [comment]
`dag-pb` seems only mentioned in the external lib called `cids` at https://github.com/multiformats/js-cid/blob/0e11f035c9230e7f6d79c159ace9b80de88cb5eb/src/cid-util.js#L14

**Comment by lidel** [comment]
If I understand correctly what ENS tooling does, it is not preserving entire CID:  something is extracting multihash chunk from original CID  and then put it into your own HEX-encoded thing which uses `ipfs-ns` or `ipns-ns` codec.

This worked fine for CIDv0 (which look the same  as multihash in base58), but does not work for CIDv1, because you are losing metadata like cid version and cid codec. 

When you convert multihash (CIDv0) to base32 you need to convert it to CIDv1, and that is where implicit `dag-pb` from CIDv0 becomes explicit in CIDv1. 

IIUC, the fix here is to modify `encode` operation and ensure full CIDv1 is stored (without base prefix), not just the multihash part.  That way codec inside CIDv1 will be preserved.

**Comment by makoto** [comment]
`ensure full CIDv1 is stored (without base prefix), not just the multihash part` can you elaborate this part a bit more?

This is the simplified version of what our `encode` is doing right now.

```
> value ='bafkreifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m'
'bafkreifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m'
> cid = new CID(value)
> cid.version
1
CID(bafkreifgdsdsniwl3njkmdi4ydq3jm6htcbz2q37gfkjegogep4epsxs4m)
> cid.codec
'raw'
> cid.multihash.toString('hex')
'1220a61c8726a2cbdb52a60d1cc0e1b4b3c798839d437f31549219c623f847caf2e3'
> cid.prefix
<Buffer 01 55 12 20>
> encodedValue = c.toV1().buffer.toString('hex')
'01551220a61c8726a2cbdb52a60d1cc0e1b4b3c798839d437f31549219c623f847caf2e3'
> multiC.addPrefix('ipfs-ns', c.toV1().buffer).toString('hex')
'e30101551220a61c8726a2cbdb52a60d1cc0e1b4b3c798839d437f31549219c623f847caf2e3'
```

in summary

storage system: IPFS (0xe3)
CID version: 1 (0x01)
content type: raw (0x55)
hash function: sha2-256 (0x12)
hash length: 20
hash: 1220a61c8726a2cbdb52a60d1cc0e1b4b3c798839d437f31549219c623f847caf2e3

which seems like retaining all the right info.

One thing I am not sure is our `decode` function which always uses `b58MultiHash`

```
  b58MultiHash: (value) => {
    const cid = new CID(value);
    return multiH.toB58String(cid.multihash);
  },
```

which always return v0 version (Qm..), not v1 version (ba...)

```
> multiH.toB58String(cid.multihash)
'QmZX5cmukMMauZJNVmbKMGXjxwyxMtxNb6Uc2juA77FiaN'
```

**Comment by lidel** [comment]
Indeed, your `encode` seem to preserve CIDv1, but the `decode` is lossy – it returns multihash in base58btc,  (ignores version and codec), so every CID gets downgraded to CIDv0:

https://github.com/ensdomains/content-hash/blob/f66f10001fe0ee03431f68a4f4fadf0d80084a5a/src/profiles.js#L104-L110

I also noticed ipns-ns encoding/decoding  is bit error-prone: does not ensure `libp2p-key` codec is present when pre-CIDv1 identifiers are used.

Opened https://github.com/ensdomains/content-hash/pull/3 with suggested fixes and additional tests.
