### ISSUE TITLE
Subdomain not working on eth.link

### ISSUE THREAD

**Issue by wighawag** [ensdomains/ens-app#1126]
**Describe the bug**
I am seeing this message : `SSL certificate for alpha.conquest.eth.link is not created yet`
and when I click `Request SSL Certificate` it stays on `pending` forever 

when I reload I get the same message and button

when I click the button I can see in the console lots of 404 to : https://eth.link/names/alpha.conquest.eth.link

**To Reproduce**

1. go to http://alpha.conquest.eth.link/
2. it is not working even though the content hash is set to a working ipfs link

1. Go to 'https://app.ens.domains/name/alpha.conquest.eth'
2. Click on 'Request SSL Certificate'
4. See error in console

**Expected behavior**
no error and I should be able to navigate to http://alpha.conquest.eth.link/

**Comment by makoto** [comment]
I don't see the issue any more. Possibly the timing issue?
