### ISSUE TITLE
Do not refresh page every time checks renewal box

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1127]

**Comment by makoto** [comment]
eg: https://app.ens.domains/address/0xfFD1Ac3e8818AdCbe5C597ea076E8D3210B45df5

Currently clicking tick box or heart icon (which adds into Favourite) reloads the entire list which is quite annoying when you try to click multiple checkbox or heart button

<img width="1273" alt="Screenshot 2021-05-17 at 13 21 28" src="https://user-images.githubusercontent.com/2630/118487625-d2de2400-b712-11eb-98a9-07f9e52ee2e0.png">

**Comment by LeonmanRolls** [comment]
No longer relevant due to redesign
