### ISSUE TITLE
Showing wrong expiration dates on Favourites

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#1135]
here's an example:

What I see on Favourites:
<img width="1792" alt="Screen Shot 2021-05-15 at 4 09 37 PM" src="https://user-images.githubusercontent.com/30162762/118376793-61be3580-b587-11eb-980f-2e1c9c94f4ba.png">

Real expiration date (according to name page):
<img width="1792" alt="Screen Shot 2021-05-15 at 4 11 18 PM" src="https://user-images.githubusercontent.com/30162762/118376799-6da9f780-b587-11eb-82c2-6d8df243ca59.png">

**Comment by makoto** [comment]
Are you still seeing 2031?

<img width="1018" alt="Screenshot 2021-05-17 at 13 12 39" src="https://user-images.githubusercontent.com/2630/118486557-a970c880-b711-11eb-9962-ae773725817b.png">

I can't reproduce

**Comment by brantlymillegan** [comment]
Still showing the wrong dates for me. I think it has something to do with me adding a bunch of names to the Favourites page and they got the info jumbled somehow

<img width="1792" alt="Screen Shot 2021-05-20 at 10 37 11 AM" src="https://user-images.githubusercontent.com/30162762/118998311-95fa7300-b946-11eb-8b44-04d4c1a1c92b.png">

**Comment by brantlymillegan** [comment]
I cleared my cache and after adding three names, the expiration dates are already jumbled @makoto 

<img width="1792" alt="Screen Shot 2021-05-24 at 11 47 51 AM" src="https://user-images.githubusercontent.com/30162762/119372934-e1ce5480-bc85-11eb-94a3-6df4a1e5b8eb.png">
