### ISSUE TITLE
Manager UI breaks on invalid content hash

### ISSUE THREAD

**Issue by justelad** [ensdomains/ens-app#115]
I have updated the public resolver with a custom encoded hash through MEW.
Now, when trying to open the ENS manager - the entire UI breaks after trying to validate the hash. There's just an empty screen showing as the attached screenshot shows.

The ENS name is `justelad.eth`.

Expected behavior is that the UI should display, and the `contentHash` field should show up as invalid (flagged red?)

![2019-03-20-124021_1366x744_scrot](https://user-images.githubusercontent.com/12988138/54661590-6f91e080-4b0d-11e9-8d1d-fdfca21b477e.png)

**Comment by jefflau** [comment]
Any idea on this @makoto?

**Comment by justelad** [comment]
please reopen as this is still broken: https://manager.ens.domains/name/justelad.eth

**Comment by makoto** [comment]
Can you send me the screenshot?

Looks fine to me.

<img width="1367" alt="Screenshot 2019-04-12 at 09 49 58" src="https://user-images.githubusercontent.com/2630/56024761-9c9a7300-5d08-11e9-9e40-3f702679d223.png">

**Comment by makoto** [comment]
Make sure you do shift-command-r (for mac) to clear the cache of your page

**Comment by justelad** [comment]
for some reason now loads fine. thanks @makoto :+1:
