### ISSUE TITLE
Trim whitespace 

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1152]
Currently, it shows malformed error when user append or prepend whitespace

https://twitter.com/angelmercedes/status/1399089790755213313?s=19

It should just trim off when you search

## Acceptance criteria

- Search " foo.eth" and trim it to "foo.eth"
- Search "foo.eth " and trim it to "foo.eth "

**Comment by LeonmanRolls** [comment]
https://github.com/ensdomains/ens-app/pull/1153
