### ISSUE TITLE
Do not reload the page if no wallet is selected

### ISSUE THREAD

**Issue by chaitanyasjoshi** [ensdomains/ens-app#1163]
**Describe the bug**
The home page reloads even if I don't select any wallet to connect to.

**To Reproduce**

1. Go to https://app.ens.domains/
2. Click on Connect button on the top left corner.
3. Don't select any wallet to connect to (Close the modal).
4. Page reloads

**Expected behavior**
The page should not reload if the user does not select a wallet to connect to.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Version: 1.25.68

**Comment by LeonmanRolls** [comment]
Thanks for this, did you want to have a go at fixing it? Happy to give you some guidance.

**Comment by chaitanyasjoshi** [comment]
Yeah sure!
