### ISSUE TITLE
Eliminiate outdated explanation copy on Manager landing page

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#1171]
Eliminate the outdated explanation of what ENS on the bottom of the ENS Manager landing page, and instead make the blue part fill the screen. If people are going to the Manager landing page directly and want to learn about ENS, they can click "About" which will take them to the homepage which explains ENS.

What to eliminate:
![what to eliminate](https://user-images.githubusercontent.com/30162762/121572825-92f91c80-c9f2-11eb-9946-736a5c4c412b.jpg)

What it should look like when you're done:
<img width="1792" alt="Screen Shot 2021-06-10 at 12 45 32 PM" src="https://user-images.githubusercontent.com/30162762/121564806-d9964900-c9e9-11eb-9077-7f180a5e47db.png">

**Comment by LeonmanRolls** [comment]
https://github.com/ensdomains/ens-app/pull/1191
