### ISSUE TITLE
Change manager to support new dnssecoracljs

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1195]
Update https://github.com/ensdomains/dnssecoraclejs/pull/7 which now passes proof into Oracle with the different data structure.

Because testnet and mainnet uses a different version of DNSSEC Oracle contract, detect old/new version based on supportInterface and call appropriate package based on different versions

**Comment by Arachnid** [comment]
https://github.com/ensdomains/ens-contracts/pull/17
