### ISSUE TITLE
Avatar image does not display.

### ISSUE THREAD

**Issue by ericvitale** [ensdomains/ens-app#1323]
**Describe the bug**
Avatar image is not resolving.

**To Reproduce**

I followed the [instructions](https://medium.com/the-ethereum-name-service/step-by-step-guide-to-setting-an-nft-as-your-ens-profile-avatar-3562d39567fc) and the record is updated and correct but the image does not load.

I own the avatar.

Followed this format: eip155:1/[NFT standard]:[contract address for NFT collection]/[token ID]

ens: whoismoses.eth
avatar: eip155:1/erc721:0x3a5051566b2241285BE871f650C445A88A970edd/6599
contract address: https://etherscan.io/address/0x3a5051566b2241285be871f650c445a88a970edd
tokenURI: https://raw.githubusercontent.com/TheHumanoids/metadata/main/6599
image_url: https://thehumanoids.co/api/img/6599.jpg

**Expected behavior**
I'd expect to see the image of my avatar in my ens record and when I connect my wallet to ens service.

**Screenshots**
![image](https://user-images.githubusercontent.com/8474048/139609332-f5bb6187-ebd1-4cfc-a292-0e12c903a4ef.png)

**Desktop (please complete the following information):**

- OS: Any, windows / mac
- Browser chrome / firefox

**Additional context**

**Comment by arnaud-eb** [comment]
The NFT avatar does show up now:
![image](https://user-images.githubusercontent.com/53792888/145057548-e43ffef9-8d65-407a-9d7c-d3ce8b372d56.png)

**Comment by LeonmanRolls** [comment]
Shows for me too, @ericvitale reopen if this is still an issue
