### ISSUE TITLE
Better error page for Illegal char exception

### ISSUE THREAD

**Issue by mdtanrikulu** [ensdomains/ens-app#1370]
If an account has an illegal char ens name, the ens-app goes blank unusable state. We better suppress the error with a nice human readable error page, and give option to redirect them to the homepage.

Example;
https://app.ens.domains/address/0xC66135b1671aD1f2cAE217ff19234A77F7A0B00c

**Comment by bigint** [comment]
Happened for me too!

**Comment by royalfork** [comment]
Perhaps this is duplicate of https://github.com/ensdomains/ens-app/issues/1346?

**Comment by mdtanrikulu** [comment]
Closing this one as duplicate of #1346
