### ISSUE TITLE
Favourites screen getting crashed on marking a domain as not favourite

### ISSUE THREAD

**Issue by sasicodes** [ensdomains/ens-app#1386]
**Describe the bug**
The application gets crashed when a domain is marked as not Favourite.

**To Reproduce**
1. Go to `My Account`
2. Click on Heart Icon to mark the domain as Favourite (only if not already done)
3. Go to the `Favourites` tab and you can see your list of favorite domains.
4. Click the Heart Icon in one of the domains to undo Favourite.
5. You can see the page went blank.

**Expected behavior**
The domain should be marked as not Favorite and the screen should remove the domain from the favorites list or show no favorites found.

**Screenshots**

![2021-12-05_15-04](https://user-images.githubusercontent.com/29498872/144741283-047f10fa-fc3f-403b-9774-3167f84bfff7.png)
.
![2021-12-05_15-05](https://user-images.githubusercontent.com/29498872/144741263-53f17e5b-0782-4192-8a4e-372a1731622b.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Brave
- Version Version 1.32.113

**Smartphone (please complete the following information):**

**Additional context**

I tried to debug the code and the issue happens because of force return (maybe)
![2021-12-05_15-07](https://user-images.githubusercontent.com/29498872/144741312-04f7c675-310d-4307-9f69-d6897c71e7c0.png)

**Comment by bigint** [comment]
I can reproduce this, I'll try to fix this 🤗
