### ISSUE TITLE
Given same avatar string input, avatar appears in one ENS domain and not the other

### ISSUE THREAD

**Issue by innov8ion** [ensdomains/ens-app#1392]
Avatar appears: https://app.ens.domains/name/davidgoldstick.eth/details
- Normal meta: https://metadata.ens.domains/mainnet/avatar/davidgoldstick.eth/meta

Avatar doesn't appear: https://app.ens.domains/name/innov8ion.eth/details
- Empty meta: https://metadata.ens.domains/mainnet/avatar/innov8ion.eth/meta

Both avatar strings set to: eip155:1/erc721:0x1e988ba4692e52Bc50b375bcC8585b95c48AaD77/3067

Perhaps unrelated, but text records appear in a different order for both of these domains. In one, avatar appears before Twitter. In the other, they're switched. Why is this?

**Comment by innov8ion** [comment]
Perhaps it was a syncing issue, but the avatar issue now appears resolved.

Is the different order of text records a bug?

**Comment by innov8ion** [comment]
Now I notice the text record order is consistent.

**Comment by arnaud-eb** [comment]
The (text) record types are displayed in the order they were initially added to the resolver's records.

For the domain davidgoldstick.eth, the avatar record type was added in a separate transaction (2) after the other types (1):

(1) Txn Hash 0x1c44c6793f9c0fa275f1ec19d5d1a2ddc18503b7381c8729b5f12902c45397bd (email, url, com.twitter)
(2) Txn Hash 0xcc229765a5c77c16df3544bac8c58905c1f0c7c0c25a382f398c38c5d1c6e6b3 (avatar)

![image](https://user-images.githubusercontent.com/53792888/145243328-2ca5699c-349b-4c29-aeff-4407afb47c98.png)


... while all the types were added in a single transaction for the domain innov8ion.eth:

Txn Hash 0x67a23b5afc742951cae2182d5bf1cda2b7328cbb6dbd71c289d46672068de963

![image](https://user-images.githubusercontent.com/53792888/145243511-cd471e8f-9775-4ca7-99de-b12ab76ed89e.png)



A possible feature would be to order the record types alphabetically in ascending order but a separate issue should probably be opened for that.

**Comment by innov8ion** [comment]
Thanks. I've created this feature request: https://github.com/ensdomains/ens-app/issues/1394

Closing...
