### ISSUE TITLE
NFT avatar not owned by the wallet shows up in records and account info

### ISSUE THREAD

**Issue by arnaud-eb** [ensdomains/ens-app#1395]
**Describe the bug**
An NFT avatar set in the records page will show up in the ens manager app even though the wallet doesn’t own it. It will however not display the green owner flag.
![image](https://user-images.githubusercontent.com/53792888/145292241-77cd58f6-f76a-4f95-98c7-bad85df81c7c.png)

**To Reproduce**

1. Own an ENS name
2. Set your Primary ENS Name (reverse record)
3. Go to your ENS name records page
4. Click add/edit record and enter the following URI in the avatar field: eip155:1/erc1155:0x495f947276749ce646f68ac8c248420045cb7b5e/8112316025873927737505937898915153732580103913704334048512380490797008551937
5. Scroll down and click “Confirm”
6. When prompted, approve the transaction
7. Once the transaction is confirmed, wait for a few minutes, refresh the page and the avatar owned by nick.eth will show up next to your ENS name and next to the avatar field in the records page

**Expected behavior**
If the wallet is not the owner of the NFT specified in the URI, the ens app must treat the URI as invalid and behave in the same manner as it would if no avatar URI was specified or display an indicator that the wallet does not own it.

**Screenshots**

![image](https://user-images.githubusercontent.com/53792888/145291180-b077b262-446c-4087-9bfa-a9dd0dd2117e.png)

![image](https://user-images.githubusercontent.com/53792888/145291457-c64fc935-62af-4646-863a-03a5ca3edec8.png)

**Desktop:**

- OS: Linux 20.04.2-Ubuntu
- Browser: Chromium
- Version: 95.0.4638.69 (Official Build) snap (64-bit)
- tested on Rinkeby and Goerli

**Smartphone (please complete the following information):**
N/A

**Additional context**
The data fetched from the endpoint "https://metadata.ens.domains/mainnet/avatar/nick.eth/meta" has an "is_owner" property set to false. 
```
{
  ...
  "is_owner": false,
  ...
}
```
However the same occurs if you use in step 4 the NFT owned by brantly.eth which `is_owner`'s prop has a value of true:
eip155:1/erc721:0xb7F7F6C52F2e2fdb1963Eab30438024864c313F6/2430

![image](https://user-images.githubusercontent.com/53792888/145293723-0341db13-32a2-459d-9ea1-d80831d8bcd1.png)

**Comment by arnaud-eb** [comment]
Thanks @TateB. You're right, this is a separate issue. The way I see it there are 2 possible improvements:

1. Form validation when setting an avatar record not owned by the wallet => handled with #1387 
2. Check that the wallet owns the NFT avatar and render (or not) the avatar accordingly in records page and account info. The [ens-metadata-service](https://github.com/ensdomains/ens-metadata-service) api does provide a `is_owner` property but this is currently not used in the ens manager app to conditionally render the avatar (it displays a green owner flag in the records page if wallet owns the NFT though)

**Comment by LeonmanRolls** [comment]
I don't think the app should police the avatar record in this way, it is enough to indicate if the address owner is the owner of the NFT.

**Comment by jefflau** [comment]
The manager is more of a database for your name and records. It definitely should be shown so it can be debugged.
