### ISSUE TITLE
Register button "does nothing"

### ISSUE THREAD

**Issue by hieronymus777** [ensdomains/ens-app#1411]
**Describe the bug**
Clicking the "register" button on a new domain "does nothing".

In the console I see an error that says:
```
instrument.ts:129 fromPromise error:  Error: invalid address (argument="address", value="0x0", code=INVALID_ARGUMENT, version=address/5.4.0)
    at e.value (index.ts:225:28)
    at e.value (index.ts:237:20)
    at e.value (index.ts:241:21)
    at p (index.ts:109:16)
    at e.value (formatter.ts:235:16)
    at r.<anonymous> (base-provider.ts:1558:51)
    at f (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at o (18.4240690d-3672.chunk.js:2:897919)
```
When I go to 

**To Reproduce**
1. Install MetaMask, or Coinbase Wallet extension (also reproducible in Dapp Browser)
2. Sign in to a wallet with funds
3. Go to https://app.ens.domains/name/hippletydipplety.eth/register 
4. Approve eip1102
5. Click on "Register"
Result: nothing happens (and error is logged in console)

**Expected behavior**
Transaction confirmation UI pops up.

**Screenshots**
![image](https://user-images.githubusercontent.com/23645629/147174218-951abc6b-65a9-410d-9c5c-c5bbd5b8d8cb.png)

**Desktop (please complete the following information):**

- OS: MacOs
- Browser: Chrome
- Version 96

**Smartphone (please complete the following information):**

- Device: Android (haven't tried on ios)
- OS: Android 12
- Browser Dapp browser on Coinbase Wallet

**Additional context**

**Comment by hieronymus777** [comment]
Looks like it's working now. Going to close out this issue.

**Comment by serenae-fansubs** [comment]
Anything specific you did you fix this? Someone else might be running into the same issue.
