### ISSUE TITLE
Wallet status never shows as connected in Status.im

### ISSUE THREAD

**Issue by serenae-fansubs** [ensdomains/ens-app#1418]
**Describe the bug**
Reporting this on behalf of someone in the Discord server. When using [Status.im](https://status.im/), after searching for a name and connecting your wallet to the app, the wallet status in the top navbar never shows that you are connected.

After you visit app.ens.domains, the Status app will automatically ask the user to whether they want to connect their wallet. But even after they allow the wallet connection, after going to a domain registration page the Request to Register button is not enabled:
<img src="https://user-images.githubusercontent.com/95138671/148631109-805c7b37-e7d7-4b57-b87c-a060bb328f0a.png" height="400px"/>

If the user enters the navbar they see that their wallet still shows up as not connected. After tapping on Connect, the page appears to automatically update indicating that the wallet has connected. But the wallet status in the navbar doesn't reflect that, it still says "Read only":
<img src="https://user-images.githubusercontent.com/95138671/148631038-9abd2262-cc1b-459c-8433-c97ee9efcf90.png" height="400px"/>

**To Reproduce**
1. Open the Status app, go to app.ens.domains
2. Status will prompt you to connect your wallet, tap Allow
3. Search for the name you want and tap on it
4. Notice that although you've already connected your wallet, the page does not yet detect that
5. Open the navbar and click on Connect
6. Notice that the page does connect and the Request to Register button is enabled, but that the wallet status in the navbar still says "Read only"

**Expected behavior**
After clicking on Connect in the navbar and successfully connecting, the wallet status should show the user's address (or primary name and avatar). It should also show a Disconnect button rather than a Connect button.

**Smartphone (please complete the following information):**

- Device: Android
- Browser: Status.im in-app browser
- Version: Status.im version 1.17.0

**Additional context**
This was reported by someone on the Discord server.

**Comment by D4nte** [comment]
Pretty sure it's fixed with https://github.com/status-im/status-react/issues/12744
cc @churik

**Comment by churik** [comment]
Confirm that it is resolved in 1.18.

**Comment by serenae-fansubs** [comment]
Can confirm this is fixed in Status version 1.18, thanks!
