### ISSUE TITLE
Show expiry date for names

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#143]
When viewing a name for a registrar we support (eg, .eth), show the expiry date for the name's registration.

**Comment by jefflau** [comment]
I think we do this for the permanent registrar already. Is there something explicit you wanted for this issue?

**Comment by jefflau** [comment]
Assigned to @makoto if anything needs to be done, or it can be closed

**Comment by makoto** [comment]
@Arachnid can you be more specific? Do you mean for A: expiration date for new registrar, or B: expiration date fo old registrar? 

For A, it's been implemented for a while (screenshot attached) on our test environment but does not exist for prod env until we live release.

<img width="1436" alt="Screenshot 2019-04-15 at 10 35 17" src="https://user-images.githubusercontent.com/2630/56122496-6fe59600-5f6a-11e9-978c-7475e6a4248a.png">


 For B, the old registrar does not have expiration date on its own but should see the migration message instead like below.

<img width="1347" alt="Screenshot 2019-04-15 at 11 04 07" src="https://user-images.githubusercontent.com/2630/56124666-0c119c00-5f6f-11e9-9da1-5e0e05d172f3.png">

Let me know if you are seeing something different but if that's the case, please specify the url of the manager and the network you are connecting to.

**Comment by makoto** [comment]
Please reopen if this is still the issue.
