### ISSUE TITLE
Cannot set domain for ContentHash (DNSLink)

### ISSUE THREAD

**Issue by feld** [ensdomains/ens-app#1430]
If users want to leverage IPNS they are forced to accept a single point of failure (the IPFS server with the key for the IPNS address) unless you use DNSLink. I've consulted members of the IPFS Discord and was informed that the only way to have a fast resolving and redundant IPNS address is to use DNSLink. There are plans to add redundancy for IPNS publishing, but there's no promised release date.

Please bring this functionality back. It's already in use by others e.g., Uniswap and it works great. I have built a system around automatic pinning across multiple geographically dispersed IPFS nodes which relies on DNSLink to quickly resolve the IPFS CID and I'd really like to use it, but your frontend's input validation is breaking the ability to do so.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/40271278/150819870-f4995ebf-f7d0-4681-8602-c6aaa4149ea7.png">

![](https://user-images.githubusercontent.com/40271278/150696615-dc188063-eff2-49d9-aa86-4bd22dcb2b48.png)

**Comment by dospore** [comment]
@feld I ran into this as well. It took a couple of hours and $15 worth of gas but I managed to figure it out. Your domain encoded in an will work. Not that I am going to suggest running this unless you are willing to lose a couple dollars of gas (only tested this once).

There are a couple comments left by previous devs mentioning that anything but cryptographic I[PNS names are deprecated](https://github.com/ensdomains/content-hash/blob/master/src/profiles.js#L97-L99). Would be good to get someone who knows a bit more about ENS than I to shed some light on this

But I ran everything locally. The frontend can remain app-ens can remain unchanged.

https://github.com/ensdomains/ens-app - can remain the same
https://github.com/dospore/ui - my version of ens-ui youll have to link it with yarn link to app
https://github.com/dospore/content-hash - my version of content-hash will have to link to ui package

[Proof is in the pudding ](https://app.ens.domains/name/dospore.eth/details) here is my ens name linked up to a dnslink I have on my dospore.xyz domain.

**Comment by makoto** [comment]
Closing this PR. Please refer to https://github.com/ensdomains/ui/pull/164#issuecomment-1131514097 for the rationale.
