### ISSUE TITLE
Is it a must to set up my own subgraph?

### ISSUE THREAD

**Issue by btfdip** [ensdomains/ens-app#1445]
Can I directly use the url:

https://api.thegraph.com/subgraphs/name/ensdomains/ens

?????

which is from:

https://thegraph.com/hosted-service/subgraph/ensdomains/ens

**Comment by makoto** [comment]
Should be possible. 
Going forward, please post questions in our discord https://chat.ens.domains/  #developer channel rather than raising github issue
