### ISSUE TITLE
Cannot submit proof on DNS record

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#1450]
Clicking "Register" throws an error on console.log

**Comment by makoto** [comment]
bug ticket number "general-4506"

**Comment by makoto** [comment]
"general-4574" as well

**Comment by makoto** [comment]
and "general-4540"

**Comment by makoto** [comment]
and "general-4558"

**Comment by zadok7** [comment]
"general-4588"

**Comment by zadok7** [comment]
"general-4568"

**Comment by janurskremer** [comment]
Is it fixed? I still can’t register via DNS.

**Comment by FSW-LIFE** [comment]
do we have any info on what is causing this? I have a screenshot of what caused it to throw an error. 

![code throw on ens app](https://user-images.githubusercontent.com/54602468/159175882-190156f9-8fcc-458f-8ebb-19c8deeecfd0.png)

seems like a function was deleted from the code.... specifically the function that converts the input into hexadecimal or maybe the function that is used to read it?

**Comment by Pandapip1** [comment]
Same for me.

**Comment by makoto** [comment]
Fixed with https://github.com/ensdomains/ens-app/pull/1459/files
