### ISSUE TITLE
Not showing up as owner even though owner of avatar, also the image not showing below avatar field.

### ISSUE THREAD

**Issue by zendevil** [ensdomains/ens-app#1453]
**Describe the bug**
I own an erc 1155 and I have set it as my avatar on ens, but it doesn't have the owner tag and there's no hyperlink to the opensea page either. Also the image is not showing below the avatar field.

**To Reproduce**

1. Go to https://app.ens.domains/name/zendevil.eth/details
2. Scroll down to "avatar"
4. See that there's no green owner tag.

**Expected behavior**
It should show the owner tag.

**Screenshots**
<img width="1675" alt="Screen Shot 2022-03-17 at 16 53 17" src="https://user-images.githubusercontent.com/30054030/158893262-7937ef5f-2628-4d5b-b5e9-18c7626eb5d5.png">

**Desktop**

- OS: macOS Monterey
- Browser: Brave 
- Version 1.35.101

**Comment by makoto** [comment]
I am closing this as I can see the owner label showing up. It could be probably a timing issue and taking a bit while to update the state.

<img width="1601" alt="Screenshot 2022-03-28 at 18 01 38" src="https://user-images.githubusercontent.com/2630/160449926-f67ccfab-09d4-4549-adf0-f5075a66c7a9.png">
