### ISSUE TITLE
Cannot set reverse record if not owner

### ISSUE THREAD

**Issue by NicolasMahe** [ensdomains/ens-app#146]
After speaking with @Arachnid, here is my issue with the website.
The form to set the reverse record is only displayed when the logged account (account selected in Metamask) is the same as the owner.

But, I want to set a reverse record for a sub-domain that points to another account (not to the owner).
ENS reverse record is compatible with this functionality but the UI doesn't allow it.

- No form when not the owner of the sub-domain but the resolved address:
![image](https://user-images.githubusercontent.com/5823445/55694125-ed068d80-59f5-11e9-8c88-aca31bb4f05e.png)

- Form when owner of the sub-domain:
![image](https://user-images.githubusercontent.com/5823445/55694356-2d1a4000-59f7-11e9-967e-7cb091ba0d0c.png)

**Comment by jefflau** [comment]
This should be addressed in #150

**Comment by NicolasMahe** [comment]
@jefflau Thanks!
