### ISSUE TITLE
Resolver and all records not being loaded for domains with emojis

### ISSUE THREAD

**Issue by serenae-fansubs** [ensdomains/ens-app#1504]
**Describe the bug**
The ENS manager UI is not loading the resolver and any records for any domain/subdomain that contains emojis.

Example: [🚀🚀🚀.eth](https://app.ens.domains/name/%F0%9F%9A%80%F0%9F%9A%80%F0%9F%9A%80.eth/details)

![image](https://user-images.githubusercontent.com/95138671/169524120-c2617711-9573-4685-91db-03abfff8d65a.png)

The resolver _is_ properly set:
![image](https://user-images.githubusercontent.com/95138671/169524277-f174eaae-c010-4e26-b763-9743e3e15a7a.png)

And it works fine in other clients:
![image](https://user-images.githubusercontent.com/95138671/169524350-4c4739d3-9560-436d-a88b-b6e634c64d6e.png)

**Additional context**
Reported by multiple people on both Twitter and Discord

**Comment by streetcredit** [comment]
had the same issue and was told that the resolvers are working just not showing on the interface

**Comment by 0xWizardof0x** [comment]
I can confirm that if you had content record set, it is no longer working. My domain Charlottes🕸.eth was resolving to the set IPFS linked content in both Metamask Mobile and Brave Desktop and as of this issue, the domain no longer resolves the Content.

**Comment by Web3Master** [comment]
Sorry I’m not sure this adds anything, but tested emoji subdomain (👽.enspunks.eth) the resolver shows not set (even after adding the ENs public resolver).  The subdomain is recognized with a ✅ in MM (mobile) but the address shows the burn (0x00…0) 
![74B88FFC-AE4F-41C2-A259-982BA0C49E3E](https://user-images.githubusercontent.com/78926369/171727133-7f6d39a9-37be-49b2-b33c-65c42370b12f.jpeg)

**Comment by serenae-fansubs** [comment]
That's just because you haven't set the ETH address record yet on that subdomain. (Because you can't currently do that in the manager UI, I'm assuming)

That subdomain has the default public resolver set, so you can manually update the ETH address record against that contract. For example, on Etherscan: https://etherscan.io/address/0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41#writeContract

For that subdomain, use `0x3eff677fcc3434e177b9941e55bad3faa9cb24ff787679a92b9ded2f155a02d0` for the node.

![image](https://user-images.githubusercontent.com/95138671/171731433-be66746a-0c63-42a8-ae1e-7e6dc30ec321.png)

**Comment by streetcredit** [comment]
Will test this soon.

**Comment by Rin-Akaia-eth** [comment]
@serenae-fansubs how to calculate a proper gas limit and price for the manually created tx?

**Comment by notison** [comment]
<img width="1421" alt="Screenshot 2022-07-08 at 15 04 17" src="https://user-images.githubusercontent.com/108940837/178007742-ede7697a-5095-43ed-8a27-380e7ca8971c.png">

I tried to search my domain ( 🤠cowboy.eth ) on etherscan but it says  "Name does not follow UTS-46 normalization."
I thought ens allowed emojis as an address.  I noticed that all my domains that have an EMOJI followed by WORD have the same common denominator. On Resolver it says "No Address found"
