### ISSUE TITLE
Avatar field rejects all valid NFT-addresses

### ISSUE THREAD

**Issue by Cthulu-dot-eth** [ensdomains/ens-app#1524]
**Describe the bug**
It's currently not possible for users to set their avatar to an NFT because the string verification for the avatar field rejects any string that doesn't begin with http:// https:// or ipfs://

**To Reproduce**
Enter any valid address to an ERC-721 or ERC-1155 NFT, or simply go to Add/Edit Records on an ENS name where the avatar is already set to one.

**Screenshots**
![cant_set_avatar](https://user-images.githubusercontent.com/96479721/173222021-d640d94a-3596-4226-a525-98487a4659df.png)

**Desktop (please complete the following information):**
All operating systems, all browsers, all versions.

**Additional context**
The bug prevents people from setting their avatar.

**Comment by philipschilling** [comment]
I am having the same issue:
<img width="966" alt="Screenshot 2022-06-12 at 20 47 56" src="https://user-images.githubusercontent.com/4956295/173250444-decc87a4-38e6-4b23-ab57-1a911be14508.png">

**Comment by gurugeek** [comment]
same issue here !

**Comment by jefflau** [comment]
Deploying the fix now!

**Comment by makoto** [comment]
Fixed at https://github.com/ensdomains/ens-app/pull/1521
