### ISSUE TITLE
Subdomain lookup doesn't appear to be working

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#155]
On the permanent registrar test site, it appears that the subdomain lookup isn't working.

<img width="1667" alt="Screen Shot 2019-04-08 at 11 54 47 AM" src="https://user-images.githubusercontent.com/6430200/55738455-2985b980-59f5-11e9-93e3-fd5877502095.png">
The main domain result shows, the subdomain lookup continues to spin. 

It's either not working or takes a very long time.

**Comment by jefflau** [comment]
sub domain registrar is not on ropsten

**Comment by Arachnid** [comment]
@jefflau Hunh? There's no such thing as a subdomain registrar.
