### ISSUE TITLE
EIP-2304: inconsistency between coin type index and path component.

### ISSUE THREAD

**Issue by q9f** [ensdomains/ens-app#1588]
**Describe the bug**
The ENS apps does not consistently use the coin type index. The `AddrResolver` contract uses the following coin type index for Ethereum as default:

```solidity
uint constant private COIN_TYPE_ETH = 60;
```

This is the coin type index as defined in [SLIP-44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md).

However, if I use the ENS app to set a custom coin record, it uses the _path component,_ not the coin type index.

**To Reproduce**

1. Go to app.ens.domains
2. Set a record for a domain you control
3. Set one record for ETH and one for ETC.
4. Submit on chain
5. See below.

If I set both ETH and ETC address records for my resolver using the ENS app, it stores the ETH record using the coin type index `60` but the ETC record using the path component `0x8000003d`.

Here's the transaction event log (last entry): https://etherscan.io/tx/0x32c1eedf6d99a5458cc3f81ccbfc0f463226f131d34ada06b2364880d1f96309#eventlog

**Expected behavior**
[EIP-2304](https://eips.ethereum.org/EIPS/eip-2304#specification) specifies to use the **index** not the path:

> `coinType` is the cryptocurrency coin type index from [SLIP44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md).

The app should default to `61` for ETC, and so on, using only the coin type index.

**Screenshots**

```ruby
## using a public resolver on mainnet
resolver.address
# => "0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41"

## calling the resolver for the default record (ETH)
infura.call(resolver, "addr", ens.namehash("ncwc6edqldzy6mlo.eth"))
# => "0xde270e46d63b1816d1b798cff473c4ba238aca73"

## calling the resolver for the coin type for ETH and ETC
infura.call(resolver, "addr", ens.namehash("ncwc6edqldzy6mlo.eth"), 60).unpack('H*').first
# => "de270e46d63b1816d1b798cff473c4ba238aca73"
infura.call(resolver, "addr", ens.namehash("ncwc6edqldzy6mlo.eth"), 61).unpack('H*').first
# => ""

## calling the resolver for the path component for ETH and ETC
infura.call(resolver, "addr", ens.namehash("ncwc6edqldzy6mlo.eth"), 0x8000003c).unpack('H*').first
# => ""
infura.call(resolver, "addr", ens.namehash("ncwc6edqldzy6mlo.eth"), 0x8000003d).unpack('H*').first
# => "37287f68ac899b769faa57033c78b78c76c68dc0"
```

I can't really tell which component introduces this. I checked the [address encoder](https://github.com/ensdomains/address-encoder/blob/42b3416e1f35ceb712d0741a0fb6579c26ffe03b/src/index.ts#L1477) which uses the index correctly.

```
hexChecksumChain('ETC_LEGACY', 61),
```

**Comment by q9f** [comment]
I manually removed the coin type `2147483709` to set it back to an empty record `0x` and forced to set an `61` coin type record and now I see the following in the app.

![Screenshot at 2023-02-16 11-59-21](https://user-images.githubusercontent.com/58883403/219347063-980b3fcf-601f-46e5-ab51-61523b8775b3.png)

- `2147483709` maps to `ETC`
- `61` maps to `ETC_LEGACY`

But where is this documented?

**Comment by makoto** [comment]
Hi. any EVM chains except ETH is using ENSIP11 https://docs.ens.domains/ens-improvement-proposals/ensip-11-evmchain-address-resolution . We still leave ETH to use ENSIP9 because it's set [as a default](https://github.com/ensdomains/ens-contracts/blob/master/contracts/resolvers/profiles/AddrResolver.sol#L13) Probably we should modify ENSIP11 to exclude ETH(60) as an exception

**Comment by q9f** [comment]
Thank you. ENSIP11 answers my question. 👍🏼
