### ISSUE TITLE
etherscan link subdomain 'loading'

### ISSUE THREAD

**Issue by tabcat** [ensdomains/ens-app#1609]
https://github.com/ensdomains/ens-app/blob/2e1cc09aa65d25ea023c1755a7561c636c85c54d/src/components/Links/EtherScanLink.js#L32-L36

sometimes the `network` variable here is 'loading'. this results in the link directing to a non-existent page.

I use the app often without metamask installed.

**Comment by LeonmanRolls** [comment]
Thanks for reporting, closing this as we will be migrating to the new version of the manager app shortly
