### ISSUE TITLE
IPNS / DNSLINK in content hash

### ISSUE THREAD

**Issue by chrisschaub** [ensdomains/ens-app#1623]
**Is your feature request related to a problem? Please describe.**
It would be nice to set our content hash to ipns://foo.com if we have dnslink setup. This used to work https://github.com/ensdomains/ens-app/issues/849 but now it seems the interface won't allow it.

**Describe the solution you'd like**
It would be nice to set our content hash to ipns://foo.com if we have dnslink setup. 

**Describe alternatives you've considered**
The alternative is to use IPFS or IPNS CIDs which are not very friendly or flexible.

**Additional context**
I think this might be possible with the ethers.js api, haven't tried yet.

Or maybe this was removed? I can't tell from the previous issue 849.

**Comment by encirca-services** [comment]
Closed
