### ISSUE TITLE
Owner and controller logic seems broken for names under legacy registrar

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#164]
In the screenshot below, both the owner and controller have addresses. 

<img width="1325" alt="Screenshot 2019-04-15 at 12 02 20" src="https://user-images.githubusercontent.com/2630/56128367-50a13580-5f77-11e9-94a4-8cbc3ec9dee4.png">

"Pending" should appear only if auction is not finalised as stated at https://discuss.ens.domains/t/ui-question-for-users-who-auctioned-but-finailsed/883/9

**Comment by jefflau** [comment]
fixed
