### ISSUE TITLE
Improve discoverability for name management

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#172]
At the moment, if you view a name you don't own, there's no indication that the app supports managing that name at all. We should show some indication that this functionality exists, so people are motivated to enter a name they own or switch to the account that owns it. Perhaps always show the management UI components, but grayed out, or show a message prompting the user to log in or switch accounts.

**Comment by lyricalpolymath** [comment]
should we add a "UX" or "design" label to issues so that we can see what to address?
