### ISSUE TITLE
All pages are titled "Error finding name"

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#174]

**Comment by Arachnid** [comment]
This appears to be fixed on ensappdev.surge.sh, but is still happening on manager.ens.domains.

**Comment by makoto** [comment]
FYI, the message appears on the tab
<img width="1394" alt="Screenshot 2019-04-16 at 22 09 25" src="https://user-images.githubusercontent.com/2630/56244258-68baa700-6094-11e9-9cef-15479b49952c.png">

**Comment by makoto** [comment]
Now that dev is merged live, this is no longer happening
