### ISSUE TITLE
RPC Error: gas required exceeds allowance or always failing transaction 

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#183]
2 different situations in which this error appears
- when migrating from old registrar to new registrar (tested on ropsten, not mainnet)
- when setting contenthash (on both Ropsten and Mainnet)

### migrate problem
![Screenshot 2019-04-17 at 15 48 00](https://user-images.githubusercontent.com/516744/56300310-fe5a4300-6135-11e9-8e11-e1a9ec7de428.jpg)

### contenthash problem
![ENA-Issues_manager_contentHash_2 problems on Ropsten](https://user-images.githubusercontent.com/516744/56300160-b9cea780-6135-11e9-9b6b-93540217dcec.jpg)

![ENA-Issues_manager_contentHash_2 problems on Mainnet](https://user-images.githubusercontent.com/516744/56300171-c05d1f00-6135-11e9-9238-ecf0e2411378.jpg)

maybe this can help
https://ethereum.stackexchange.com/questions/32123/using-web3-eth-estimategas-cause-gas-required-exceeds-allowance-or-always-faili

**Comment by makoto** [comment]
Should be fixed by https://github.com/ensdomains/ens-app/pull/186
