### ISSUE TITLE
contenthash validation problem - whitespace trimming + doesn't show warning on error

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#184]
if the input text has whitespace it doesn't show an error
even though the console catches the error.
it's going to be very likely that users copy paste the hash from somewhere.

![ENS-Issues_manager_contentHashValidation](https://user-images.githubusercontent.com/516744/56300540-6e68c900-6136-11e9-8acc-6306e8c683a2.jpg)

**Comment by jefflau** [comment]
Not really sure what we should do here. We could show an error, or just trim the whitespace and then validate? @makoto

**Comment by makoto** [comment]
Trim is more user friendly but text record allows whitespace so we should add validation error message to be consistent across multiple types?
