### ISSUE TITLE
resolver record creation - transaction pending loop shown before actual transaction

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#185]
when attempting to launch a transaction to create a Record in the Resolver
the TX pending loop is shown even if a transaction is never sent 
like in case of issue https://github.com/ensdomains/ens-app/issues/183

expected behavior: the TX loop should be shown only if the TX has actually been sent out

see issue 2 
![ENA-Issues_manager_contentHash_2 problems on Ropsten](https://user-images.githubusercontent.com/516744/56300662-a7a13900-6136-11e9-9559-6d0627a7a33c.jpg)

**Comment by makoto** [comment]
I think this is related to https://github.com/ensdomains/ens-app/issues/183 which is now fixed. Please check if this is still happening or not
