### ISSUE TITLE
Owner/Controller terminology

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#192]
Currently non .eth domains (subdomains/DNSSEC) are still called owner. We should rename them to controller to be consistent. The CTA buttons should change dependent on whether they are the controller or the owner. If they are relinquishing control then it should be 'transfer', if they are not it should be 'set'

**Comment by chris-remus** [comment]
Regarding - 

"The CTA buttons should change dependent on whether they are the controller or the owner."

Is this -

"If they are relinquishing control then it should be 'transfer', if they are not it should be 'set'"

...the only change that happens, as a result of making the above choice, or are there other dependencies, e.g. entirely separate paths. If there are, do you have everything you need to implement each path?

**Comment by jefflau** [comment]
Yeah exactly. It's just about whether they lose control or not
