### ISSUE TITLE
404 on .xyz names

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#209]
eg: https://manager.ens.domains/name/ddd.xyz 

If user click the page directly it shows 404 (no matter of which network it is connected).
The same problem does not appear when tested on localhost. Also .eth and .luxe names are fine

**Comment by jefflau** [comment]
I think it's something to do with the way surge is reading the url. If I add another `/` at the end, it works. I may have to add something after to make it work on surge like `https://manager.ens.domains/name/ddd.xyz/`

**Comment by makoto** [comment]
@jefflau if I think through, it does not make sense that it only appearns on `.xyz` but not on others.

**Comment by makoto** [comment]
Noticed it also happens on https://manager.ens.domains/search/matoken.org and https://manager.ens.domains/search/matoken.com , but not https://manager.ens.domains/search/matoken.net nor other domains.

**Comment by makoto** [comment]
Added an issue to surge https://github.com/sintaxi/surge/issues/374

**Comment by makoto** [comment]
Was a bug on surge and it is fixed https://github.com/sintaxi/surge/issues/374
