### ISSUE TITLE
"Resolver is outdated" error

### ISSUE THREAD

**Issue by john-light** [ensdomains/ens-app#211]
When I set the public resolver as the resolver of my domain on Ropsten with https://manager.ens.domains/ I am shown the error:

![resolvererror](https://user-images.githubusercontent.com/9424721/56826371-f030b480-6810-11e9-9af2-972f1e78d71e.png)

**Comment by jefflau** [comment]
This is most likely because we have no updated the resolver.eth on Ropsten. Can you confirm @Arachnid. If it has been updated then we probably have an error in our logic @makoto

**Comment by makoto** [comment]
Yes, I am aware of this and raised an issue here a while back https://github.com/ensdomains/ens/issues/328
