### ISSUE TITLE
name/auctionedtoorecent.eth shows migration modal

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#228]
name/auctionedtoorecent.eth is created within 28 days locking period but it shows migration modal (clicking the button throws error). 

<img width="1304" alt="Screenshot 2019-04-30 at 23 08 37" src="https://user-images.githubusercontent.com/2630/56996681-341f1300-6b9d-11e9-93f5-c5832c4e1638.png">

**Comment by jefflau** [comment]
I'll leave this to you @makoto

**Comment by makoto** [comment]
Looks like the bug was introduced in this refactoring https://github.com/ensdomains/ens-app/commit/e9a022dd#diff-a81ce19c239c033e25af8fa93156f4f8R193

Here is the PR to fix https://github.com/ensdomains/ens-app/pull/236
