### ISSUE TITLE
Renewal button layout look  broken on mobile

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#237]
<img width="735" alt="Screenshot 2019-05-01 at 11 34 02" src="https://user-images.githubusercontent.com/2630/57016089-31a9d100-6c10-11e9-9fed-d8b40648bc0d.png">

**Comment by jefflau** [comment]
This is low priority. This only happens if you open renew and then reduce the screen size, which is only really what you'd do if you were 'pretending' to be on mobile by reducing the browser size. I'm removing permanent tag

**Comment by makoto** [comment]
Just checked and no longer happening
