### ISSUE TITLE
USD pricing not visible if user has 3rd party script blocker extension

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#241]
Problem: The client doesn't get the pricing in USD if it has extension for 3rd party script blocker.

Solution: add a warning / "info icon button" tooltip with a text like:

> We couldn't load the price in USD. You might have have a browser extension that is stopping 3rd-party scripts, in our case from Etherscan, that we use for the currency conversion. Disable it for our site if you want the convenient USD currency conversion.

Problem
![Screenshot 2019-05-01 at 18 37 44](https://user-images.githubusercontent.com/516744/57029277-8ade2880-6c41-11e9-8b4d-d5b69dab8bbb.jpg)

![Screenshot 2019-05-01 at 18 44 40](https://user-images.githubusercontent.com/516744/57029276-8ade2880-6c41-11e9-86bb-b1a70ac08b7c.jpg)

**Comment by lyricalpolymath** [comment]
the same problem (or a similar one) happens in Brave due to the Shield up feature

![Screenshot 2019-05-02 at 16 28 33](https://user-images.githubusercontent.com/516744/57084698-1071df00-6cfb-11e9-93b3-2262de9132b4.jpg)

**Comment by makoto** [comment]
I don't think we can do anything about it as it seems blocking any Cross origin request. One workaround is to proxy through backend server from the same origin but we do not have backend server. @Arachnid any other workaround we can think of? Maybe we should just show a warning saying it fails to fetch USD price from external source?

**Comment by Arachnid** [comment]
No workaround I'm aware of. We should handle errors gracefully and just not show the field, though.

**Comment by lyricalpolymath** [comment]
showing the warning was a UX solution that could at least offer the users a way to get the convenient USD pricing
In the first screenshot there is a red `(i)` where I would put the info tooltip component that the manager already displays somewhere else
