### ISSUE TITLE
[Manager] not set Resolver shows as 0x000

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#242]
Show "No Resolver Set"  and no blockie
rather the 0x000 

(it behaved like this as you can see in Chris's screenshot here https://github.com/ensdomains/ens-app/issues/216.
maybe I missed the decision to change this?

![Screenshot 2019-05-01 at 19 08 18](https://user-images.githubusercontent.com/516744/57030594-89166400-6c45-11e9-9274-597b547c2785.jpg)

**Comment by makoto** [comment]
Closing this as we now automatically set resolver
