### ISSUE TITLE
[Permanent Registrar] - details and subdomains button visible during registration

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#255]
The 2 buttons should not be visible while you register the domains
the "heart" button is ok that is visible, but should be aligned to the right

![Screenshot 2019-05-03 at 21 35 37](https://user-images.githubusercontent.com/516744/57161302-8190bf80-6deb-11e9-8cb5-8eef4918e92e.jpg)

**Comment by jefflau** [comment]
Fixed in #258
