### ISSUE TITLE
Cannot transfer registrant

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#259]
Tried to transfer registrant of https://manager.ens.domains/name/breaktheblock.eth (which I am owner of) on Mainnet and got the following errors (no metamask popup)

<img width="444" alt="Screenshot 2019-05-04 at 21 11 04" src="https://user-images.githubusercontent.com/2630/57184288-7a33e980-6eb1-11e9-861e-0a910784248d.png">

**Comment by makoto** [comment]
I tried on my local machine with Ganache and have no issues. Strange...

**Comment by jefflau** [comment]
Should be fixed by #265
