### ISSUE TITLE
Support ENS names in address input fields(!)

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#261]
For instance, I can't transfer a name to an ENS name. This is a bit embarrassing.

**Comment by makoto** [comment]
Is this as simple as followings?

1. For any fields which requires you to type hex address (transfer owner of registrants/controllers, set resolver, address) if user type ENS name, then lookup ENS and convert to hex if there are matches.
2. If no matches, shows "invalid" warning (as currently does).

A few clarifications

- Do we show both ENS name and hex address if reverse record are set when user is not editing (like our logged in user field on the top left)?
- Does the scope include setting contenthash as well?

**Comment by Arachnid** [comment]
> For any fields which requires you to type hex address (transfer owner of registrants/controllers, set resolver, address) if user type ENS name, then lookup ENS and convert to hex if there are matches.

Depends what you mean by 'convert'. We should leave the original text as-is, but resolve it to its address. This is a good place for us to show users the best-practice for resolving ENS names in a UI.

> Do we show both ENS name and hex address if reverse record are set when user is not editing (like our logged in user field on the top left)?

Absolutely.

> Does the scope include setting contenthash as well?

I think this is less useful, since it would only work to set a content hash to another domain's content hash.

**Comment by makoto** [comment]
- @Arachnid will do all the coordination
- Beltran has to publish the best practice guide

**Comment by Arachnid** [comment]
@chrischinchilla Would it be possible to arrange a Gitcoin bounty for a React component that displays and accepts ENS addresses?

**Comment by Arachnid** [comment]
Obsoleted by #315.

**Comment by ChrisChinchilla** [comment]
@Arachnid I only have budget for docs bounties, sorry!

**Comment by Arachnid** [comment]
@chrischinchilla no worries!
