### ISSUE TITLE
Reverse record for a subdomain pointing to domain address instead of subdomain address

### ISSUE THREAD

**Issue by alexfisher** [ensdomains/ens-app#263]
I migrated alexfisher.eth to the permanent registrar, added a resolver, added a subdomain "wallet" and added a resolver for wallet.alexfisher.eth.

alexfisher.eth is controlled by 0xc606f
wallet.alexfisher.eth address record points to 0x4a8f64

Adding a reverse record and the app will only allow me to Save the record with a default value of 0xc606f.

The Reverse Resolution translates an address into a name. It allows Dapps to show in their interfaces “wallet.alexfisher.eth” rather than the long address. I want dapps to show wallet.alexfisher.eth for 0x4a8f64... not 0xc606f3.

![ens-wallet alexfisher eth](https://user-images.githubusercontent.com/176891/57194463-412d6080-6f15-11e9-9ca0-d98c8d2a0e4e.JPG)

I'm attempting to do all this within my PC's browser, using metamask, which of course is signed in to 0xc606f (the controller).

**Comment by jefflau** [comment]
Can you try signing into 0x4a8f64 and then going to wallet.alexfisher.eth and see if you can save a reverse record?

**Comment by alexfisher** [comment]
Yes, that worked.  In this case, I had a dapp browser on the other wallet and device.  Is there a reason not to enable management of everything from the controller address/dapp browser?

**Comment by makoto** [comment]
@alexfisher the reverse record can only be set by the owner of the address. Would be problematic if anyone can set the reverse record of the address they don't own and we as a dapp only know that you own the address if you logged in with the address. Having said that our reverse record admin us is not optimal so we consider changing in near future.

**Comment by makoto** [comment]
I will close this for now unless it turned out to be an actual bug @alexfisher
