### ISSUE TITLE
add link to https://manager.ens.domains/ from https://registrar.ens.domains/

### ISSUE THREAD

**Issue by jennypollack** [ensdomains/ens-app#264]

**Comment by jefflau** [comment]
There does appear to be a link in the modal from registrar.ens.domains. Although maybe we should just get rid of the old registrar since it's pretty much 100% deprecated now

 @Arachnid Maybe we can just redirect directly to the manager?

**Comment by Arachnid** [comment]
Yup. We can ditch the registrar now, as it's completely useless.
