### ISSUE TITLE
Add the label hash and namehash for a name somewhere they can be easily copied.

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#274]
As mentioned by @Arachnid at https://discuss.ens.domains/t/permanent-registrar-immediate-post-launch-triage/976/2

Do we potentially need new UI/Design?

**Comment by lyricalpolymath** [comment]
@makoto more than "permanent registrar" this should be labeled "manager" ?
I've added this conversation on https://discuss.ens.domains/t/ux-ui-manager-should-we-and-where-to-show-namehash-labelhash-other-advanced-information/977
so that Becca can respond too

**Comment by brantlymillegan** [comment]
Closing since this is duplicated in another Issue
