### ISSUE TITLE
Make the tool capable of looking up any node in the system, including the ENS root.

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#275]
As mentioned at https://discuss.ens.domains/t/permanent-registrar-immediate-post-launch-triage/976/2

**Comment by jefflau** [comment]
This has mostly been done. You can navigate to a root by clicking on the parent of a subdomain e.g. `vitalik.eth` can navigate to `eth` via the parent. You can also use the URL bar and manually type in /name/eth
