### ISSUE TITLE
Unable to set/change controller. Error: Returned error: The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by industral** [ensdomains/ens-app#278]
Trying to set/change controller, get JS error:

```Error: Returned error: The method eth_sendTransaction does not exist/is not available```

<img width="1680" alt="Screen Shot 2019-05-07 at 5 42 34 PM" src="https://user-images.githubusercontent.com/331772/57309048-0cc1cc00-70f0-11e9-842b-13f2d2e102fa.png">

**Comment by jefflau** [comment]
This should be fixed in #279.

Please let me know if it is!
