### ISSUE TITLE
Update Time Display

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#285]
Timestamps don't indicate AM or PM. They're not in 24 hour format, either. My suggestion is to display them in 24 hour format.

First reported [here](https://twitter.com/poppyknows/status/1126168859696926720?s=19).

![Screen Shot 2019-05-08 at 1 13 47 PM](https://user-images.githubusercontent.com/6430200/57394497-b3ab7400-7193-11e9-974e-756fdbfbf62c.png)

**Comment by lyricalpolymath** [comment]
we can even skip the time probably and show only the year

but if we want to show the time
I would get rid of the  "seconds" (they are adding only visual clutter to the UI)
