### ISSUE TITLE
add a subdomain that you know exists but that you aren't seeing in the list

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#291]
Problem: there is currently no way to add a subdomain that you know should exist but is not showing in the list

Possible solution: when clicking `Save`, first check if the subdomain already exists 

UX/UI improvements required
possibly add a label to explain it: "if you own a subdomain and aren't seeing it here you can try to add it and when you click save we'll search it for you"

this is not directly related to #240 
but when thinking the UX for this feature, consider the requirements of that issue too

![Screenshot 2019-05-09 at 12 39 11](https://user-images.githubusercontent.com/516744/57448029-bae88580-7258-11e9-8dfe-5c85a64c7d1e.jpg)

**Comment by makoto** [comment]
It can now add to local storage by searching the name (though it should add into local storage upon the name creation which is tracked in other github issue)
