### ISSUE TITLE
Issue with transaction receipt  (imToken browser)

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#292]
Phillip from imToken:

```
1. I entered this ENS name
2.  Bought it for 0.1 years
3. Confirm tx. See below:
https://etherscan.io/tx/0xd4b5ccd47f044213aac6b14560cacbb2135ea5a51e7694490d22dbd7897364a3
4. Waited 3 minutes, but nothing happens
5. Close dapp browser
6. Open dapp browser
7. Open ens manager
8. Enter some random characters and click enter
9. Click favorites and get back to the page I left earlier
10. The site looks just like I hadn't sent any tx. See screenshot attached. I actually expected that it shows that I already paid.
```

Issue seems to be related to getting a transaction receipt. Still need to confirm this as it's possible the transaction was just being slow and took > 2 mins

Edit: Initial issue has been fixed by setting `.on` to null if it detects `window.imToken`. We should look into removing this if we upgrade web3, and or adding web3Read to reading tx status to bypass going through imToken's node

**Comment by p0s** [comment]
Jeff:
> It looks to me like it’s nothing to do with the waiting itself, it has the ’tx pending’ and the event itself is never triggered. Depending on the blockchain itself there are one of two things that could have happened:
> 
> 1) You didn’t wait long enough and the tx is still pending (sometimes 2-3 mins is not long enough depending on network traffic)
> 2) There is something wrong with fetching the transaction receipts which updates the next part of the UI (where the bar will start to fill up). Please have a go on ropsten on desktop to see what i mean

I'm very confident that it's reason (2), because 
1. I waited 2 minutes after the first tx, and then opened etherscan, where the tx already had more than 10 confirmations
2. Mako and other colleagues had the same experience

**Comment by p0s** [comment]
Opening the URL https://manager.ens.domains/?___debug=1 in imToken gives you a browser console, fyi.

**Comment by p0s** [comment]
@jefflau Can you look into it?  @sapjax is available for questions here

**Comment by jefflau** [comment]
I may not have time to sort it out today. But I will do my best. What version of imToken are you looking at? I am downloading the iOS version now

**Comment by jefflau** [comment]
How do I setup imtoken on ropsten?

**Comment by p0s** [comment]
@jefflau , yes, simply the latest imToken 2.0 on iOS app store is fine.
You can't use it on Ropsten :/ imToken can show Ropsten balance, but the DApp browser cannot do Ropsten (and other testnet) tx.

For the browser console, you may need to activate developer mode (not sure):
Click 'My Profile' -> Click 'About Us' -> Click imToken logo 8 times.

Also, you may find useful information on https://docs.token.im/dapp-sdk/en/

**Comment by jefflau** [comment]
@p0s if I can't do ropsten or local transactions it's going to be pretty expensive to try and debug this. From what i can see though it's something to do with web3's transaction receipt. It works fine on browser, but I'm not sure why it's not working on imToken.

**Comment by p0s** [comment]
@jefflau Yea, that sucks. There's literally real cost for us not supporting ropsten. We already paid a couple of USD in ETH yesterday for testing. You only need to pay the gas though. You can set the ENS domain rental time really low.

I remember, having a similar issue with Loom, maybe that helps: https://github.com/loomnetwork/dashboard/issues/382
https://github.com/loomnetwork/dashboard/issues?utf8=%E2%9C%93&q=is%3Aissue+imtoken

Let me know in case you need our side for testing.

**Comment by jefflau** [comment]
@p0s I don't think that sounds like a future proof solution. There is possibly many bugs associated with imToken, not just the one. Minimum rental time for ENS is 1 month.

Is it possible for you guys to support ropsten?

**Comment by p0s** [comment]
@jefflau you're right. We know the issue, and it's in the backlog. 
For this issue here, we can't provide it though. We would like to support ENS lets say latest until mid next week. But ropstens support is more like for somewhere in the next half year, even if.

I could reimburse the 5-10 USD it costs though! Seriously.

**Comment by jefflau** [comment]
0x866B3c4994e1416B7C738B9818b31dC246b95eEE here is my address. I'll look into testing it on Monday. No promises on fixing it before mid next week as I don't even know if it's an issue on our end or on imToken or possibly a web3 issue

**Comment by sapjax** [comment]
It looks like that our ethereum parity node didn't enable the `eth_subscribe` function for RPC request.
I will take care of the node issue,  then we can test it again.

**Comment by Aaaaaashu** [comment]
Can we use web3Read instead of web3 to read the transaction status? This way ENS Manager can call `eth_subscribe` directly via infura.

**Comment by sapjax** [comment]
@jefflau 
Please look into this PR: https://github.com/ensdomains/ens-app/pull/296
I tested it, and it works now.

**Comment by jefflau** [comment]
@Aaaaaashu Yes we can do that if it fixes the bug - Can you open another PR for it?

**Comment by jefflau** [comment]
@Aaaaaashu Actually I just realised that this might be tricky to do as we do not separately poll the chain for the receipts, we use the `web3.send().on` functionality so it would be a bigger job than just 'using web3Read'
