### ISSUE TITLE
MetaMask + Chrome or Brave: The method eth_sendTransaction does not exist/is not available

### ISSUE THREAD

**Issue by funkyland** [ensdomains/ens-app#298]
I'm unable to transfer registrant in Chrome and Brave using MetaMask:

```
Uncaught (in promise) Error: Returned error: The method eth_sendTransaction does not exist/is not available

at Object.ErrorResponse (errors.js:29)

at index.js:125

at XMLHttpRequest.i.onreadystatechange (index.js:80)
```

"Set controller" is working fine, but registrant transfer gives the following error in the console.

**Comment by jefflau** [comment]
I have pushed a fit in the latest release. Let me know if it is fixed

**Comment by funkyland** [comment]
Working perfectly now, thank you!
