### ISSUE TITLE
ENS Favourites page blanks out after idle

### ISSUE THREAD

**Issue by physikal** [ensdomains/ens-app#317]
Browser: Brave Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
URL: https://manager.ens.domains/favourites

After leaving a tab on the above URL idle for a while, I go back to that tab and the screen is blank. Not sure on how long you have to stay idle.  Even refreshing the page does not clear it up.  However, if I close the tab then re-visit manage.ens.domains, do a search, then click favourites the page loads just fine.  When it does load fine, no errors in dev console.  When it is blanked out I get these errors in the dev console: https://imgur.com/a/Q0CURa7

**Comment by jefflau** [comment]
I left mine open for about 20 mins but i didn't get get the blank page. I'm also using Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

Are you on Mac OSX?
Are you using Metamask?

**Comment by physikal** [comment]
I'm on Windows 10 and yes I am using Metamask.  Tomorrow I will open a
fresh instance of it then time it for you.  I've only tried it from work so
it could be some agent causing it as well.  Fireeye, DLP, who knows.

**Comment by jefflau** [comment]
Okay thanks that will be really helpful to try and figure out how to replicate it so I can fix it. Appreciate you taking the time!

**Comment by jefflau** [comment]
Is it possible it's related to this? https://github.com/ensdomains/ens-app/issues/273

**Comment by physikal** [comment]
Sounds similar but all my domains that are in the favourites page have been
migrated to the new ens.

**Comment by physikal** [comment]
Ah, just read the rest. It could be related to the count.  I have 6-7 on my
favourites.

**Comment by jefflau** [comment]
Hmm, well let me know how long it takes/or a more reliable way to recreate. I wonder if it's to do with the domains themselves you favourited. Maybe you can try emailing me jeff [at] ens.domains the domains you have favourited if that is needed to recreate it (if you don't mind).

**Comment by physikal** [comment]
Alright I have successfully reproduced with a time as well, but one
additional step to get it to repro.

Browse to https://manager.ens.domains
search: any domain
Click Favourites
Sit on favourites page for 27 minutes, click refresh (or F5).  Then it
reloads blank.


After writing these repro steps it occured to me it would be nice to have a
favourites button on the root page of ENS Domains.
