### ISSUE TITLE
Can't purchase domain

### ISSUE THREAD

**Issue by bandrebandrebandre** [ensdomains/ens-app#319]
I have favorited the domain I wish to purchase, and despite the fact that my 'request to register' transaction has gone thru, the "Register" button never appears in the browser. Running metamask 6.5.1, macos 10.14.4, latest chrome.

**Comment by jefflau** [comment]
Do you see "tx pending" or does the green bar start to move? Do you mind videoing your experience so I can see what's going on?

**Comment by bandrebandrebandre** [comment]
Sure, I'll post a video in a few hours when I have access to a computer
again.

**Comment by bandrebandrebandre** [comment]
Just tried it again and it worked fine. If I remember correctly, I was getting no green bar action whatsoever.
