### ISSUE TITLE
Show a warning or error for invalid names

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#327]
Reported here: https://discuss.ens.domains/t/non-compliant-name-on-official-lookup-https-manager-ens-domains-name-rainbow-eth/992

https://manager.ens.domains/name/%F0%9F%8C%88rainbow.eth is not a valid name per nameprep, but we don't show any indication of that.

We should probably still show the user the info on the name, but with a large warning at the top that the name is not valid and will not resolve in browsers/wallets etc.

This also relates to our behaviour for https://github.com/ensdomains/ens-app/issues/282 - when someone looks up a non-normalised name, we should redirect them to the normalised version, and show an alert that this happened, offering them a way to view the original non-normalised version.

**Comment by Arachnid** [comment]
I just checked, and this name *does* pass uts-46 normalisation, which ENS uses. IDNA also uses uts-46, but it must be using a more restrictive set of permitted characters.

Nevertheless, we need to improve our handling of invalid or non-normal names.

**Comment by joshuawu** [comment]
UTS-46 normalisation is part of the IDNA protocol. So for UTS-46 to make any sense, ENS needs to adhere to the IDNA standard.
You can read more about UTS-46/IDNA here: https://unicode.org/reports/tr46/
Since 2003 the set of valid codepoints has been defined as the union of CONTEXTJ, CONTEXTO, and PVALID under any version of Unicode from 5.2 on. Presently this means that emoji are definitely illegal, and any compliant registrar will not accept emojis.
The reasoning behind excluding emojis is described in this advisory from ICANN: https://www.icann.org/en/system/files/files/sac-095-en.pdf

**Comment by Arachnid** [comment]
> UTS-46 normalisation is part of the IDNA protocol. So for UTS-46 to make any sense, ENS needs to adhere to the IDNA standard.

I don't think this is true. UTS-46 is part of IDNA, but that doesn't mean that UTS-46 is meaningless without the rest of IDNA.

For anyone else reading, the rest of our conversation is here: https://discuss.ens.domains/t/non-compliant-name-on-official-lookup-https-manager-ens-domains-name-rainbow-eth/992/11

**Comment by kclowes** [comment]
@Arachnid I'm working on standardizing the web3py ENS module to the manager. I've been reading through the UTS46 spec and EIP137, and I am a little confused. EIP137 says:
> Labels and domains may be of any length, but for compatibility with legacy DNS, it is recommended that labels be restricted to no more than 64 characters each, and complete ENS names to no more than 255 characters. For the same reason, it is recommended that labels do not start or end with hyphens, or start with digits.

I take this to mean that these are recommendations, not rules. Yet, https://manager.ens.domains enforces that names are at least 7 characters, and don't start or end with hyphens. Starting with a number is acceptable in the manager. However, AIUI, UTS46 only optionally enforces the hyphens, and optionally enforces that the label length is between 1-63. Does the EIP need to be updated to include these restrictions, or is there a reason it doesn't have stricter language? Also, is there somewhere I can reference a list of restrictions from the manager? Thanks!

**Comment by Arachnid** [comment]
> Yet, https://manager.ens.domains enforces that names are at least 7 characters, and don't start or end with hyphens. Starting with a number is acceptable in the manager. However, AIUI, UTS46 only optionally enforces the hyphens, and optionally enforces that the label length is between 1-63.

The limitation of 7 characters should only be on .eth, and is specific to the manager. I'd like to remove it entirely.

In general, any ways in which the manager deviates from UTS-46 are a bug in the manager, not in EIP 137. Please treat 137 as authoritative here.

**Comment by kclowes** [comment]
Great, that is what I needed to know! Thanks!

**Comment by makoto** [comment]
@Arachnid is this still an issue? Both Metamask and Etherscan seem to resolve 🌈.makoto.ethglobal.eth though

<img width="354" alt="Screenshot 2019-09-03 at 17 00 03" src="https://user-images.githubusercontent.com/2630/64189604-83878f80-ce6c-11e9-9212-0028f1e12e15.png">
<img width="684" alt="Screenshot 2019-09-03 at 17 00 21" src="https://user-images.githubusercontent.com/2630/64189605-83878f80-ce6c-11e9-8cf4-50de3de27760.png">

**Comment by Arachnid** [comment]
@makoto The rainbow is valid per uts-46, so this should be fine.

**Comment by makoto** [comment]
@Arachnid the rainbow is used the test failed case. can you give me an example I can use to test?
