### ISSUE TITLE
Can not transfer a subdomain back to parent owner

### ISSUE THREAD

**Issue by zediir** [ensdomains/ens-app#338]
After transferring a subdomain to another account as the original owner of the parent domain I can't reclaim ownership of my subdomain through the ens app. In this case I controlled both private keys but if I transfer a subdomain to a key that I don't control it would be nice to be able to gain the ownership back without having to do the transaction manually.

**Comment by jefflau** [comment]
I'll take a look at this

**Comment by jefflau** [comment]
I've fixed this in the most recent deploy - can you check if it works on your end?

**Comment by zediir** [comment]
Works. I am able to set the controller. 👍

**Comment by zediir** [comment]
Only minor thing is that now the parent owner will always see "set" instead of "transfer" on their subdomains even if they are still the controller.
