### ISSUE TITLE
AppId is showing 'React app' in android add to home screen link

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#339]
<img width="328" alt="Screenshot 2019-06-03 at 12 30 42" src="https://user-images.githubusercontent.com/1221141/58776175-dc405580-85fb-11e9-8003-dd13ab5f5837.png">

**Comment by makoto** [comment]
Fix deployed at  https://github.com/ensdomains/ens-app/releases/tag/v1.1.9
