### ISSUE TITLE
Show disabled transfer/set/etc buttons when a user is not the registrant/controller

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#346]
The fact we don't display any functionality for updating records when the user isn't signed in as the owner hurts discoverability; many people don't realise that functionality is available at all. Instead, we should show the buttons, but disable them, with a tooltip explaining why.

**Comment by jefflau** [comment]
Think we need input from Becca on this. If it is as simple as making them all greyed out that will be an easy fix, but I'm sure there are some edge cases that could use her input. @rliebert

**Comment by rliebert90** [comment]
@Arachnid I think you had similar feedback a while back about showing the write-app functionality when a user isn’t logged in or when a name is unavailable. My solution was to show the buttons and edit icons greyed out. If you hovered over a button or icon, you’d get a message explaining why it’s disabled.

**Comment by rliebert90** [comment]
@jefflau and @Arachnid the language/labels in these screenshots are outdated, but this is what I described above looks like: 

<img width="926" alt="disabled-bttns" src="https://user-images.githubusercontent.com/45074845/58889403-d65b7a80-86b6-11e9-8d85-ef8a5533da10.png">

<img width="910" alt="disabled-bttns-hover" src="https://user-images.githubusercontent.com/45074845/58889412-dbb8c500-86b6-11e9-8ee6-dbf201cb0623.png">

**Comment by Arachnid** [comment]
@rliebert90 Yes, that looks perfect to me.

**Comment by jefflau** [comment]
closed by #356
