### ISSUE TITLE
Need relative path support to run ens manager as a true dapp.

### ISSUE THREAD

**Issue by homotopycolimit** [ensdomains/ens-app#352]
I have been experimenting with getting the ENS manager running as a dapp (as opposed to a server-hosted web app).

Following https://facebook.github.io/create-react-app/docs/deployment#building-for-relative-paths, I have modified package.json before compiling, but this is not enough to get it to work. 

The end result is: 
<-your-swarm-node->/bzz:/bb250f83a182ef05c0456040aabc46a6432fd74cea98bb51a912dc7a2fe9822a/

It seems that there are still many hard-coded absolute paths in the code (as well as references to 'manager.ens.domains'?). 

I'd welcome any help in compiling a static version of this app using relative paths everywhere so that we can deploy it as a dapp on Swarm.

**Comment by jefflau** [comment]
Hi @homotopycolimit,

The only thing I can think of that is possibly affecting this is react router and the build script for CRA. Does it work at all and images and links break? Or does it not work at all?

**Comment by homotopycolimit** [comment]
it does not seem to work at all.
