### ISSUE TITLE
support IPNS in contenthashes + show the stored content string even if wrong

### ISSUE THREAD

**Issue by lyricalpolymath** [ensdomains/ens-app#358]
we know that this domain is using an IPNS hash (not IPFS)
https://manager.ens.domains/name/www.wealdtech.eth (on mainnet)

can we support it and make it show?
cc @makoto 

In any case, if the content inserted is wrong we should still show what it is, and show the warning sign that it is malformed. right now it can't be "debugged" by a user of the manager 

![Screenshot 2019-06-11 at 10 39 20](https://user-images.githubusercontent.com/516744/59257420-33ff4200-8c36-11e9-93b6-624db44a41e6.jpg)

**Comment by makoto** [comment]
That's pending on Jim's PR on multicodec to be mreged https://github.com/multiformats/multicodec/pull/136 . Once done, then we need to ask https://github.com/pldespaigne/content-hash to support IPNS

**Comment by lidel** [comment]
Note that `/ipns/` paths are mutable, which means content behind such address can change without the need for updating anything in ENS.

Are you sure you want to allow that type of pointer in ENS?
My impression was that ENS contracts are deterministic and always point at immutable content, but maybe it is not a requirement?

**Comment by etam** [comment]
@lidel 
Ens supports also bzz, onion and onion3 addresses. Bzz can be a [Feed](https://swarm-guide.readthedocs.io/en/latest/dapp_developer/index.html#feeds), which is mutable, just like IPNS. Onion addresses can return dynamic content, like any http server. Your argument is invalid.

**Comment by etam** [comment]
@makoto https://github.com/pldespaigne/content-hash/pull/30 is done.

(disclaimer: I'm not involved in any development. I just registered my ENS domain and was surprised that I can't use IPNS hash)

**Comment by hacdias** [comment]
@makoto pinging just to ask if there are any plans to support this. This is a must-have feature and having a first-hand support on the ENS app would be awesome 😄

**Comment by NoahZinsmeister** [comment]
adding some additional context:

Uniswap recently migrated its interface entirely to IPFS (https://uniswap.org/blog/ipfs-uniswap-interface/). as part of this transition, the contenthash of `uniswap.eth` was set to `/ipns/app.uniswap.org`. however, this had to be done manually because it's not supported in the ens app, and it also doesn't display correctly in the ens app. would love to see native IPNS support.
