### ISSUE TITLE
Search Results Page Won't Resolve in Firefox

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#38]
Firefox v63.0

Summary -

Search results page appears blank after searching on a name.

Steps -

1 - Navigate http://ensappdev.surge.sh/

2 - Allow Metamask to connect

3 - Type "chrisremus" or "chrisremus.eth" into search box

4 - Hit "Return)

Console output -  

ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code. inpage.js:1:1206
Dapp browser active with injected ethereum object web3.js:36:12 

TypeError: "i is undefined" value http://ensappdev.surge.sh/static/js/main.a8d7ac45.chunk.js:1:139401 value http://ensappdev.surge.sh/static/js/main.a8d7ac45.chunk.js:1:91804 render http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:16001 ai http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:892926 oi http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:892721 di http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:896878 Gi http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:911869 Ki http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:912246 Iu http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:918738 Pu http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:918118 ku http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:917139 Ji http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:916042 enqueueForceUpdate http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:880762 forceUpdate http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:828784 updateCurrentData http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:13573 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:13269 y http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:938949 m http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:939455 value http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:940072 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:343202 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:343155 queryListenerForObserver http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:681556 broadcastQueries http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:686874 broadcastQueries http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:686854 broadcastQueries http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:686748 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:687932 y http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:938949 m http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:939455 value http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:940072 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:668132 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:668098 y http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:938949 m http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:939455 value http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:940072 next http://ensappdev.surge.sh/static/js/1.7580c053.chunk.js:1:745516react-dom.production.min.js:3841

TypeError: i is undefined[Learn More] ReverseRecord.js:12:19

**Comment by jefflau** [comment]
Should be fixed now. Can you check? @chris-remus
