### ISSUE TITLE
Claim .test domain on Rinkeby : Network error

### ISSUE THREAD

**Issue by hefgi** [ensdomains/ens-app#381]
Hi guys,

I'm trying to use the manager to claim a domain but I'm getting a Network error in the console (for example https://manager.ens.domains/name/thisisatest.test). A friend of me tried as well and was able to reproduce the same.

Here's the error while I click on Claim button : 
```
Uncaught (in promise) Error: Network error: sending a transaction require a signer (operation="sendTransaction", version=4.0.31)
```

I'm using Metamask 6.7.2 (and I'm on the Rinkeby network) and Chrome Version 75.0.3770.100.
Same is happening using Brave Version 0.66.99 Chromium: 75.0.3770.100

**Comment by jefflau** [comment]
Thanks for this report. I will look into this

**Comment by jefflau** [comment]
I fixed the error, but as far as I'm aware we don't have a .test registrar on rinkeby. Registration works fine in ropsten though
