### ISSUE TITLE
Compatibility issue of some low cellphone version

### ISSUE THREAD

**Issue by zhen6939** [ensdomains/ens-app#389]
Hey there, 
I encountered a blank screen while opening ENS Dapp on imToken 2.0.

The following images show the issue:
![image](https://user-images.githubusercontent.com/6891736/61194941-947f1480-a6f7-11e9-9fde-cf84a344ac6f.png)

It seems like ENS Dapp doesn't consider the compatibility of some lower cellphone systems.
It can be reproduced on the android v5/v6 phone and some iPhones(lower than ios v11) 

Please have a look at it.

**Comment by jefflau** [comment]
Hi @zhen6939,

Do you have anyway I can reproduce this bug without an android V5/v6 or a lower iPhone? 

Looks like it's related to `react-spring` which is a library we use for animations.

**Comment by makoto** [comment]
We can try to add polyfill in our end using [this](https://facebook.github.io/create-react-app/docs/supported-browsers-features#configuring-supported-browsers).

According to https://caniuse.com/#feat=object-entries Android < 4.4.4 and Safari < 10 do not support `Object.entries` which is throwing the error. What version do you guys want us to try to support?

Makoto

**Comment by xwartz** [comment]
@makoto 

[caniuse.com](https://caniuse.com/#feat=object-entries) shows the mobile browser, but the webview version may be lower than the browser.

The following configuration works on Android < 6 and iOS < 11.
https://facebook.github.io/create-react-app/docs/supported-browsers-features#configuring-supported-browsers

```
"browserslist": {
  "production": [
    ">0.2%",
    "not dead",
    "not op_mini all"
  ]
}
```

**Comment by makoto** [comment]
@xwartz the version with your config info is deployed to  http://productive-magic.surge.sh/ Can you check if it works with the url?

**Comment by xwartz** [comment]
![image](https://user-images.githubusercontent.com/4149827/61681103-a2a7e300-ad3e-11e9-81db-f7f2c11ebc65.png)

It doesn't work.

**Comment by makoto** [comment]
Can you try with this one ? http://humorous-lumber.surge.sh
I upgraded `react-spring` which has `"targets": ">0.05%, not dead, not ie <= 11, not op_mini all"`  https://github.com/react-spring/react-spring/commit/cce8a649b74fc7076911a0784b4cd38a17291a41

**Comment by xwartz** [comment]
It didn't work until I added the object polyfill https://github.com/ensdomains/ens-app/pull/409
