### ISSUE TITLE
Investigate running thegraph locally

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#393]
We are about to push some new features which are powered by the graph. However these features cannot be tested on our local environment. We need to be able to run the graph locally so we can still use Cypress tests.

**Comment by makoto** [comment]
I created the instruction as a gist https://gist.github.com/makoto/1a2fe5ea968a21f004ea3c2bf193849f

Once done, then this branch should work https://github.com/ensdomains/ens-app/tree/the-graph-2

**Comment by makoto** [comment]
NOTE: In my instruction, none of labelName seem set. I raised the issue with thegraph team so will update the instruction if it requires additional step
