### ISSUE TITLE
Manager not loading if not logged-into Metamask

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#411]
Note: Manager loads in incognito mode for both Brave and Firefox.

**Brave - Version 0.66.101 Chromium: 75.0.3770.142 (Official Build) (64-bit)**

Before logging into Metamask - 

<img width="1677" alt="Screen Shot 2019-07-24 at 9 16 28 AM" src="https://user-images.githubusercontent.com/6430200/61797199-eb21d800-adf4-11e9-9c77-15726c2fe025.png">

After logging into Metamask - 

<img width="1669" alt="Screen Shot 2019-07-24 at 9 17 13 AM" src="https://user-images.githubusercontent.com/6430200/61797205-ed843200-adf4-11e9-8444-619ddf0b6e92.png">

**Firefox - Quantum 68.0.1 (64-bit)**

Before logging into Metamask -

<img width="1669" alt="Screen Shot 2019-07-24 at 9 17 13 AM" src="https://user-images.githubusercontent.com/6430200/61797298-202e2a80-adf5-11e9-9b05-f79c080ef8bb.png">

After logging into Metamask - 
 
<img width="1677" alt="Screen Shot 2019-07-24 at 9 16 28 AM" src="https://user-images.githubusercontent.com/6430200/61797293-1d333a00-adf5-11e9-96cc-9d1e823bb88a.png">

**Comment by brantlymillegan** [comment]
This appears to be fixed
