### ISSUE TITLE
Subdomains are assigned the old resolver address

### ISSUE THREAD

**Issue by magford** [ensdomains/ens-app#414]
Subdomains from ENSnow are being set to the old resolver 0x1da022710dF5002339274AaDEe8D58218e9D6AB5

This is prompting a message in the manager recommending to update it.

**Comment by jefflau** [comment]
@Arachnid is it possible to update the resolver from ENSNow?

**Comment by Arachnid** [comment]
Hm, the registrar code fetches the current resolver from resolver.eth: https://github.com/ensdomains/subdomain-registrar/blob/master/app/js/app.js#L69

**Comment by jefflau** [comment]
Closing this. Reopen if this is an issue
