### ISSUE TITLE
Current controller account unable to set a new controller address of a subdomain on manager.ens.domains site

### ISSUE THREAD

**Issue by ChainLinkGod** [ensdomains/ens-app#418]
As the owner of a subdomain (mew.chainlinkgod.eth) I am unable to transfer controller to a new address on the site manager.ens.domains when using MetaMask logged into the current controller's address (chainlinkgod.eth)

https://manager.ens.domains/name/chainlinkgod.eth
https://manager.ens.domains/name/mew.chainlinkgod.eth
![image](https://user-images.githubusercontent.com/51770471/62755183-d1ed6e00-ba27-11e9-9275-d33509d2ad94.png)

**Comment by jefflau** [comment]
I'll take a look at this today

**Comment by jefflau** [comment]
This should have been fixed and deployed. Can you confirm for us and close the issue if so?

**Comment by ChainLinkGod** [comment]
Yes this fixed my problem and I was able to transfer the controller to another account
