### ISSUE TITLE
Reverse record showing incorrect reverse name

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#42]
<img width="1116" alt="screen shot 2018-11-15 at 13 27 43" src="https://user-images.githubusercontent.com/1221141/48773940-b5a27900-ecc0-11e8-9823-da79d3516a13.png">

Bug reported by @Arachnid where the reverse name is showing the incorrect name

**Comment by fubuloubu** [comment]
Also experiencing this problem. It apparently isn't letting me overwrote the field either?

![Screenshot_20191110-081535_Opera beta](https://user-images.githubusercontent.com/3859395/68544544-3951eb80-0392-11ea-99e9-7205539b05b1.jpg)
