### ISSUE TITLE
Address Detail page

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#425]
Add etherscan link, possibly amount of ETH owned for a small detail page for each address so there is something shown when there aren't any domains (also for addresses with domains)

**Comment by rliebert90** [comment]
@jefflau here's my sketch file for the address detail page: https://www.dropbox.com/s/9337wru82q51ind/ENS_Hash-detail-view_08.20.19.sketch?dl=0

I have two version. V1 has a bttn that takes you to etherscan and a list of domains owned, V2 has that and also shows the balance of eth and it's value (this is reusing the styling from the registrar detail). There's also a view of the hash that doesn't own any domains. Let me know if you have any feedback! Here are the jpgs...

![1_Hash Detail View V1](https://user-images.githubusercontent.com/45074845/63387350-30451580-c373-11e9-8265-624eba49091c.jpg)
![2_Hash Detail View V2](https://user-images.githubusercontent.com/45074845/63387351-30451580-c373-11e9-9eeb-f8989a1a0bf6.jpg)
![3_Hash Detail - No Names](https://user-images.githubusercontent.com/45074845/63387352-30451580-c373-11e9-8d8c-46d6f4b04803.jpg)
