### ISSUE TITLE
Address portfolio not updated after releasing

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#464]
> I'm also having trouble with the indexing. I released a bunch of domains, but they are still showing up next to my address. There's no ability to manually reindex an address' portfolio of domains.

From @woodydeck

**Comment by jefflau** [comment]
@woodydeck I'm assuming you mean you had some domains, which were listed under `/address/[YOUR_ADDRESS]` and then when you released them they are still listed. Is that correct?

**Comment by jefflau** [comment]
@woodydeck Also is it possible to know the address/name or an example you are using so we can debug? If it's sensitive you can email me at jeff [at] ens [dot] domains

**Comment by woodydeck** [comment]
Please search address 0xCC3d8656166d738a2B3C96Cd475405c668352989. It should have <8 domains left. 

I think just adding a reindex button is the best solution. The slightly more complicated way is to listen for changes on the ENS contract and to reindex addresses transacting. This would accommodate those transacting from other places. A cron job to reindex seems bad.


Cheers,

Woody

**Comment by jefflau** [comment]
Hi @woodydeck,

Thanks for the email. We are using a graph sub node to sync the events so we'll have to look at our indexing function and see if we made any mistakes.
