### ISSUE TITLE
Search Results Page Detail Button Not Working in Firefox

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#49]
Firefox v63.0.1

Summary -

Nothing happens when the Details buttons on the search results page is clicked.

Steps -

1 - Navigate to https://manager-beta.ens.domains

2 - Allow Metamask to connect

3 - Type "chrisremus" or "chrisremus.eth" into search box

4 - Hit "Return"

Try and click any of the "Details" buttons https://manager-beta.ens.domains/search/chrisremus

<img width="1666" alt="screen shot 2018-11-27 at 3 32 48 pm" src="https://user-images.githubusercontent.com/6430200/49109836-c2dbdc80-f259-11e8-95c6-05d307328612.png">

**Comment by chris-remus** [comment]
@jefflau The Details buttons do work in Chrome.

**Comment by jefflau** [comment]
Closing this. Reopen if it's still an issue
