### ISSUE TITLE
Basic Multicoin support

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#492]
Reuse text record components and use a hardcoded coin list

https://eips.ethereum.org/EIPS/eip-2304

Non-exhaustive list:
BTC
BCH
LTC
RSK
ETC
XRP
MONA
EOS
ATOM
XLM
LEO
DOGE
ZEC
POA
CLO
GO
VET
VTHO
WAN
TRX
ICX
TOMO
BNB
DASH
XZC
XTZ
ZIL
QTUM
DCR
AE

**Comment by hewigovens** [comment]
Address in each chain might be different, base58 encoded, base32 encoded, bech32 encoded, raw hex etc. maybe just store as string?

**Comment by makoto** [comment]
I will close this as basic ones are integrated.
