### ISSUE TITLE
Native segwit address support

### ISSUE THREAD

**Issue by hewigovens** [ensdomains/ens-app#498]
When I tried to save a native segwit address, I got this error: 

![image](https://user-images.githubusercontent.com/360470/66886246-513f8500-f009-11e9-9f6c-ea221e3e3f2c.png)

from https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2304.md, bitcoin or litecoin address is base58check-decoded bytes, this is not always the case

**Comment by hewigovens** [comment]
Although we can store the witness in raw bytes, but we still need a standard that everyone can follow

**Comment by makoto** [comment]
@hewigovens we recently updated our Manager which integrates with https://github.com/ensdomains/address-encoder . Could you let me know if you are still facing the issue?

**Comment by hewigovens** [comment]
thanks, it's fixed
