### ISSUE TITLE
Clarify In-Process Auction State Display

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#50]
Chrome Version 70.0.3538.110 (Official Build) (64-bit) (suspected same behavior in Firefox too)

Summary -

In-process auction state counts down bid period, then begins counting up when reveal period is entered. Shows state as Bidding Period, even when in reveal period.

Steps -

1 - Navigate to https://manager-beta.ens.domains

2 - Allow Metamask to connect

3 - Find an auction close to entering reveal period, by scrolling back a few days on the [twitter.com/ensbot account](https://twitter.com/ensbot).

4 - Hit "Return"

<img width="1649" alt="screen shot 2018-11-28 at 1 02 33 pm" src="https://user-images.githubusercontent.com/6430200/49172038-e9f3e600-f30d-11e8-89c8-ca994bd8b157.png">

You'll see the Bidding period count down from "a few minutes" to "a few seconds", then start counting back up from "a few seconds" to "a few minutes", while still displaying "Bidding Period".

**Comment by jefflau** [comment]
Had the reveal period mistakenly to 2 days. Also another bug I fixed where it was display the wrong hours. Let me know if this looks fixed!

**Comment by chris-remus** [comment]
The countdown seems to be working correctly in Firefox. A couple things - 

1 - The number displayed uses quite a few decimal places, once the countdown is displaying minutes, it also went negative for some reason. 

<img width="1096" alt="screen shot 2018-12-07 at 3 37 12 pm" src="https://user-images.githubusercontent.com/6430200/49671530-3ccc4c80-fa36-11e8-94db-d3fc52a414a2.png">

2 - The reveal period countdown appears to start from 49 hours, rather than 48

<img width="1102" alt="screen shot 2018-12-07 at 3 37 32 pm" src="https://user-images.githubusercontent.com/6430200/49671560-55d4fd80-fa36-11e8-87b1-c29b96057571.png">

**Comment by jefflau** [comment]
Should have fixed these now. Can you please confirm?

**Comment by jefflau** [comment]
Closing. Reopen if still an issue
