### ISSUE TITLE
Manager doesn't let me add CashAddr BCH addresses

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#513]
Manager doesn't let me add CashAddr format BCH addresses. However, if I add a BCH address in the legacy format, it displays it in the records in the CashAddr format. (The formats represent the same address and are interchangable, but I should be able to enter the CashAddr format when adding a BCH address).

**Comment by jefflau** [comment]
Can you explain the differences between CashAddr and the legacy format? I guess this is something that the addr decoder library should handle

**Comment by brantlymillegan** [comment]
It's just an encoding issue. Here's a website that converts between them: https://cashaddr.bitcoincash.org/

Here is the CashAddr spec: https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md

The main problem is that the Manager does not allow me to add a BCH address in CashAddr format, it only allows me to add in the legacy format, even though it then displays that legacy address format in the CashAddr format in the records. The key thing is I should be able to add either format when I'm adding a BCH record.

**Comment by jefflau** [comment]
Paging in @makoto as he added the extra coins

**Comment by makoto** [comment]
@brantlymillegan can you send me the following three info so that I can debug better?

- The input value
- The expected output value
- The actual value you are getting

**Comment by brantlymillegan** [comment]
Nevermind, I think I figure out why it was wrong, I was not including the "bitcoincash: " prefix. I'll close this. @makoto
