### ISSUE TITLE
Tx pending when dropped and replaced with higher fees from metamask without refreshing page

### ISSUE THREAD

**Issue by 0xc0de4c0ffee** [ensdomains/ens-app#516]
Tx that UI is waiting for  https://etherscan.io/tx/0xdeab096969e75b012a92bc6f85d2c7c177549760d4b8deadd36349753f57ded8

New Tx with bumped fees to drop and replace old tx. 
https://etherscan.io/tx/0x8c0f4790d7babadbfc1575115c96a01ca185a1c2ef95fdb02fb6c9148bf094f6

![image](https://user-images.githubusercontent.com/43116881/68575222-b44efb00-0493-11ea-93a7-7a1caa6b0b5c.png)

**Comment by makoto** [comment]
Just did quick research. There is PR on metamask to implement [EIP-2381](https://eips.ethereum.org/EIPS/eip-2831) but it seems not merged  

https://github.com/MetaMask/metamask-extension/issues/9174

Will keep this into "Blocked" for now

**Comment by GregTheGreek** [comment]
Hey! Author of eip2831! We're starting the implementation in web3.js this week :)
