### ISSUE TITLE
Some emojis can't be used in names in our Manager

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#518]
Some emojis are flagged as unsupported characters, and it appears they are all fairly newer emojis. Examples include 🦜 and 🥶. See screenshot for example error.
![Screen Shot 2019-11-11 at 5 14 21 PM](https://user-images.githubusercontent.com/30162762/68625280-bec6c000-04a6-11ea-971d-4d04b10db598.png)

**Comment by makoto** [comment]
As the error says, it is unsupported character.

Our [ENS doc states](https://docs.ens.domains/contract-api-reference/name-processing#normalising-names) that ENS follows a standard called UTS46 and the uts46 library is throwing errors as illegal characters. We can't change the behaviour only on our manager, as most other wallets and dapps use the same library (if they integrated by following our doc) and breaks compatibility.

If you have suggestions for better warning messages, that's possible to add/make changes.
