### ISSUE TITLE
UI display problems in Manager on mobile

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#519]
See pictures. I've put red marks near problem areas. Getting mobile looking and working right is really important since many mobile wallets like TrustWallet are adopting ENS and sending users to our Manager in their mobile app to register and manage their ENS name.

Both screenshots are in Brave on my Android phone. One is on the page for brantly.eth, the other on the page for brantly.xyz.

![brantly eth record](https://user-images.githubusercontent.com/30162762/68732403-1c7f0900-0588-11ea-8fb1-b00468f7d85a.jpg)
![brantly xyz record](https://user-images.githubusercontent.com/30162762/68732405-1c7f0900-0588-11ea-8240-aab8b7eb8029.jpg)

**Comment by brantlymillegan** [comment]
Additionally, I was just made aware that there is no "+" button to add a new record type on mobile

**Comment by makoto** [comment]
Fixed at https://github.com/ensdomains/ens-app/pull/635
