### ISSUE TITLE
Unable to Create Subdomains

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#52]
Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Firefox 63.0.1 (64-bit)

Summary - 

Unable to create subdomains of owned domain.

Steps -

1 - Navigate to https://manager-beta.ens.domains

2 - Allow Metamask to connect

3 - Search for name

4 - Click on Details button for owned name on search results page

5 - Click Subdomains

6 - Click Add Subdomain

7 - Enter subdomain, see green check mark, Save button does not activate

<img width="1666" alt="screen shot 2018-11-29 at 1 40 31 pm" src="https://user-images.githubusercontent.com/6430200/49313164-72ac8680-f4b4-11e8-81a8-96148bf405c1.png">

**Comment by jefflau** [comment]
Should be fixed now.

**Comment by chris-remus** [comment]
I'm able to create a subdomain in Firefox now 👏 Chrome testing pending...

**Comment by chris-remus** [comment]
Looking good on Firefox too 👍
