### ISSUE TITLE
Allow user to type any type of text record

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#521]
Currently users can only add several known fields.
Add and display any keys.

Needs to be for multicoin and text records. This also needs to be added to the resolver migration check

NOTE: This probably needs a bit of design consideration for UI to allow users to type any keys.

**Comment by jefflau** [comment]
Added some extra information about where this needs to be updated as we'll need this for resolver migration record check and the migration itself

**Comment by makoto** [comment]
Pending on https://github.com/ensdomains/ens-subgraph/pull/14 to be merged and  deployed

**Comment by makoto** [comment]
Done at https://github.com/ensdomains/ens-app/pull/631
