### ISSUE TITLE
Add ATOM , XCASH and XLM support

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#522]
Include these changes into ens-app

https://github.com/ensdomains/address-encoder/pull/10 (need to merge)
https://github.com/ensdomains/address-encoder/pull/4
https://github.com/ensdomains/address-encoder/pull/3

**Comment by okwme** [comment]
any updates on this?

**Comment by makoto** [comment]
@okwme 

I was waiting for ZCASH version to be merged but looks like it's going nowhere so created PR which merges the rest.

https://github.com/ensdomains/ens-app/pull/550

The test version is deployed into http://proud-good-bye.surge.sh/name/makoto.eth

Please let me know if there are any issues.

**Comment by okwme** [comment]
thanks @makoto !
I tried setting one for cloversnetwork.eth pointing to a new ATOM address I just generated. The transaction went through and there's a section for "other addresses" on the page but I don't see the address displayed.
https://proud-good-bye.surge.sh/name/cloversnetwork.eth

When I try to add another "other address" configuring for xDAI I submit an Ethereum address and just get the loading symbol. In the console I see:
```
cloversnetwork.eth XDAI 0xFa398d672936Dcf428116F687244034961545D91
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
resolvers.js:421 TypeError: Cannot read property 'decoder' of undefined
    at registry.js:699
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at o (asyncToGenerator.js:25)
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
```

**Comment by okwme** [comment]
🙌
