### ISSUE TITLE
Add options for logging in / Integrate WalletConnect?

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#524]
This is more about reviewing PR and test

- [x] = [Gnosis team integrate the functionality](https://github.com/Velenir/ens-app/tree/2/WC_button+autoconnect)
- [ ] = [Come up with final UI ](https://discuss.ens.domains/t/wallet-connect-new-ui/1286)
- [ ] = Implement UI change
- [ ] = Merge the PR and deploy

**Comment by Arachnid** [comment]
What is this blocked on?

**Comment by brantlymillegan** [comment]
I think Coinbase Wallet may be waiting to launch their ENS support (which Sid said they have complete) until we get Wallet Connect added to our Manager
