### ISSUE TITLE
Text record URL record should be clickable

### ISSUE THREAD

**Issue by dfinzer** [ensdomains/ens-app#539]
@jefflau: As discussed with @Arachnid, we'd like to make the presentation of URL's a bit more prominent and, most importantly, clickable. OpenSea is using this as a way to link people to the sale for the domain, and it currently is pretty difficult for users to discover how to get there.

**Comment by jefflau** [comment]
Thanks for this. We're currently busy with another sprint, but I've added this to our public development board for triaging for a later one

**Comment by brantlymillegan** [comment]
When we do this, would be great to also make Twitter and Github text records clickable to those profiles.

**Comment by makoto** [comment]
Fixed at https://github.com/ensdomains/ens-app/pull/633
