### ISSUE TITLE
Controller can't be changed with subdomains

### ISSUE THREAD

**Issue by Otherbright** [ensdomains/ens-app#544]
Hi,

It never asks to validate a transaction to Metamask and the web app keeps saying "TX PENDING":

![image](https://user-images.githubusercontent.com/594556/70638422-26546480-1c39-11ea-9b57-85d9600f2047.png)

I tried it on Google Chrome and Brave, it's not working.

Cheers,
Jonathan

**Comment by jefflau** [comment]
Hi Jonathan,

Do you mind having a look at the console to see if there is an error message there? And if so paste the screenshot in here?

Thanks,

Jeff

**Comment by Otherbright** [comment]
Hi Jeff,

Here is output of the console: 

chrome-extension://iecodoenhaghdlpodmhooppdhjhmibde/contentscript.js:265 This website is not whitelisted
VM13:140 DomDistiller debug level: 0
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for safeTransferFrom
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
resolvers.js:396 Error: Illegal char [
    at n (uts46.js:28)
    at r (uts46.js:47)
    at Object.toUnicode (uts46.js:111)
    at s (index.js:28)
    at registry.js:571
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at o (asyncToGenerator.js:25)
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr
ethers.min.js:628 WARNING: Multiple definitions for addr
ethers.min.js:628 WARNING: Multiple definitions for setAddr

Cheers,

Jonathan

**Comment by brantlymillegan** [comment]
@Otherbright Are you still experiencing this problem?

**Comment by Otherbright** [comment]
No, it has been solved with an update some months ago

>
