### ISSUE TITLE
Fix blockchain timing for name register

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#545]
Currently the timer for registering a name is using a client side timer. This makes is simpler, however sometimes the transaction fails as the register happens less than 1 min before the next block. 

One solution could be using timestamp of the block that the commit came in and make sure another block has a time `>` than that before allowing the register button to be clicked.

**Comment by donaldwazowski** [comment]
Maybe it’s off topic, but.
Where can we read about the procedure for the case, when we have 2 or more requests to register in on 1 minute interval.
Who will be able to successfully make the second transaction, to finish the registration?

Thank you.

**Comment by jefflau** [comment]
> Maybe it’s off topic, but.
> Where can we read about the procedure for the case, when we have 2 or more requests to register in 1 minute interval.
> Who will be able to successfully make the second transaction, to finish the registration?
> 
> Thank you.

Both I believe. Whoever gets their 2nd tx in first will get the name. It’s not about the earlier commit but the first reveal.

**Comment by donaldwazowski** [comment]
@jefflau , it’s
“...you have to wait for another minute to ensure no one else is trying to register your name. “ in step by step instruction.

But where is the option if someone else is trying to register the domain?
Is there some algorithm for this case provided in documentation or instructions?

**Comment by brantlymillegan** [comment]
Closing since the discussion moved to our forum: https://discuss.ens.domains/t/simultaneous-ens-registration-conflict/121/6
