### ISSUE TITLE
'No Accounts' bttn missing when not connected to metamask

### ISSUE THREAD

**Issue by rliebert90** [ensdomains/ens-app#56]
Chrome Version Version 71.0.3578.80 (Official Build) (64-bit)

Summary: 

If you don't connect to metamask, the 'no accounts' bttn doesn't appear on the landing page or search results page. 

Steps:

1 - Navigate to https://manager-beta.ens.domains

2 - Don't connect to metamask

3 - Notice there is no 'no accounts' on landing page

4 - Search for a name

5 - Area in side nav where 'no accounts' would be has a perpetual loader / bttn never appears

<img width="1118" alt="screen shot 2018-12-10 at 10 35 16 am" src="https://user-images.githubusercontent.com/45074845/49743158-273e6900-fc68-11e8-980f-52daed970dd4.png">

**Comment by rliebert90** [comment]
<img width="1440" alt="screen shot 2018-12-10 at 10 49 35 am" src="https://user-images.githubusercontent.com/45074845/49743809-8f417f00-fc69-11e8-9d04-d7ed6df02b86.png">

**Comment by rliebert90** [comment]
<img width="1440" alt="screen shot 2018-12-10 at 10 57 48 am" src="https://user-images.githubusercontent.com/45074845/49744468-d7ad6c80-fc6a-11e8-90b1-710def48d322.png">

**Comment by jefflau** [comment]
Is this still an issue @rliebert90? I'm not sure if I managed to fix this with some of the other changes.

**Comment by rliebert90** [comment]
@jefflau the no accounts button appears now when I'm not logged in - so no longer an issue!
