### ISSUE TITLE
Unable to register ens name

### ISSUE THREAD

**Issue by SomerEsat** [ensdomains/ens-app#569]
I'm attempting to register an ens name. Transaction 1 succeeds, 1 minute wait succeeds, register button doesn't work. It doesn't do anything when I click on it (nothing happens - e.g. wallet doesn't open).

I have attempted this multiple times, including restarting the browser (Brave with metamask extension).

![Capture](https://user-images.githubusercontent.com/60827187/74091523-4358b880-4a6d-11ea-8d92-f250fb1645ce.JPG)

Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Comment by Arachnid** [comment]
Registrations are disabled until Monday 1700 UTC. The UI shouldn't have been enabled again, sorry about that.

**Comment by SomerEsat** [comment]
Oh, ok, thanks.
