### ISSUE TITLE
Display thumbnail of avatar listed in text records

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#585]
Would be great to display a thumbnail (e.g. could be 300px x 300px or something similar), directly under the avatar text record field. This makes the avatar text record field more "real" in the Manager.

**Comment by makoto** [comment]
Will set to 180px following this https://blogging.com/social-media-image-sizes/

**Comment by makoto** [comment]
Added at https://github.com/ensdomains/ens-app/pull/643

**Comment by brantlymillegan** [comment]
@makoto Looks great! Do you think the record should still show the URL of the avatar? I'm thinking of the URL being clickable and in line with the avatar text record key, with the thumbnail right below the URL of the avatar. Or is that unnecessary? What do you think on this?
