### ISSUE TITLE
Handle migrating resolvers with unsupported records more gracefully

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#586]
At present, if someone tries to migrate a resolver with a record we don't understand - such as a contenthash record we don't know how to decode - we throw a JS error.

Two things to fix here:
 - We don't need to decode contenthash records in order to migrate them, we can just copy them over without understanding them.
 - If we encounter an error trying to migrate a record, we should catch it, explain we can't migrate that record, and offer to migrate the rest.

**Comment by jefflau** [comment]
Fixed the first one. Added an error message popup for the second. Maybe we should split this into two tickets. One for the fix of the first one and the second one can be investigated more thoroughly.

After removing the contenthash decoding, I think that should be all known records migrating so far.
