### ISSUE TITLE
Deploy to production via Travis errors in app

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#595]
<img width="639" alt="Screenshot 2020-02-19 at 15 58 12" src="https://user-images.githubusercontent.com/1221141/74814684-ccf06c00-5332-11ea-82b2-80f07a30b548.png">

Seems to be using an old/cached version of the resolver ABI

**Comment by brantlymillegan** [comment]
@jefflau Just going through a bunch of these old issues and trying to figure out what can be closed and should be added to our backlog. Should this be added to our backlog?
