### ISSUE TITLE
Bug: Can't migrate ENS domain

### ISSUE THREAD

**Issue by NiklasKunkel** [ensdomains/ens-app#597]
Getting the following error when trying to click the migrate button in the ENS manager in Coinbase Wallet.

https://imgur.com/a/qsysCCj

**Comment by pydlv** [comment]
I'm getting this problem too using Brave with connected wallet...

**Comment by jefflau** [comment]
I have deployed a possible fix - can you try one more time?

**Comment by pydlv** [comment]
> I have deployed a possible fix - can you try one more time?

Seems to work now. Thank you.
