### ISSUE TITLE
> Interestingly I successfully migrated using : http://ensappdev.surge.sh/

### ISSUE THREAD

**Issue by twiettwiet** [ensdomains/ens-app#598]
> Interestingly I successfully migrated using : http://ensappdev.surge.sh/
> with https://app.ens.domains I get the error mentioned above

This actually worked! Thanks...

_Originally posted by @techmental in https://github.com/ensdomains/ens-app/issues/568#issuecomment-589979445_

How to know if  http://ensappdev.surge.sh/ can be trusted?

**Comment by jefflau** [comment]
Closing this as it's been fixed!
