### ISSUE TITLE
Add Error Message

### ISSUE THREAD

**Issue by jonassunandar** [ensdomains/ens-app#599]
Hi ENS team, 

I found this error when open https://app.ens.domains/

![image](https://user-images.githubusercontent.com/18476100/75128355-418e2680-56f6-11ea-92d3-2e5b5ced9037.png)

The reason is my Metamask is in my private network and not in Main Eth Network. That would be great if there is a message that states the user has to be in Main or Test Network in order to use the app. I am afraid the non-developer user would think the site is broken.

Thank you in advance!

**Comment by jefflau** [comment]
Thanks for the input!
