### ISSUE TITLE
How to port ens app to another EVM chain

### ISSUE THREAD

**Issue by luckyyang** [ensdomains/ens-app#602]
## Found
We deployed ens contracts to our EVM chain and graph node is running successfully:
https://testgraph.elaeth.io/subgraphs/name/luckyyang/ela-ens/graphql

We registered domain successfully with contract.
 
## Issue
We want to connect ens-app to contracts and graph node we deployed, tried modified several places, but finally got errors.

I could not find the documents about how to do it, anyone could help? Thanks.

Those are the files I modified:
![image](https://user-images.githubusercontent.com/1963646/75269044-44dafc80-5833-11ea-8c9e-7f6ad08ee7c1.png)

This is the error screenshot:
![image](https://user-images.githubusercontent.com/1963646/75269287-a0a58580-5833-11ea-9f5e-97a1685e00ca.png)

**Comment by brantlymillegan** [comment]
@luckyyang Could you tell me more about what EVM chain and your goals? Would love to discuss to see how we could collaborate. If you're interested, feel free to email me at brantly@ens.domains

**Comment by luckyyang** [comment]
It's been fixed and deployed to https://eladomain.netlify.app/ , thanks @brantlymillegan ！

**Comment by luckyyang** [comment]
Refer to our repo https://github.com/luckyyang/ela-ens-subgraph/tree/mainnet if anyone have issues to port ens app
