### ISSUE TITLE
Bug: no "Return" button to get deposited eth back

### ISSUE THREAD

**Issue by ttdonovan** [ensdomains/ens-app#603]
Using this article as a reference:

https://medium.com/the-ethereum-name-service/ens-registry-migration-is-over-now-what-a-few-things-to-know-fb05f921872a

I do not see a "Return" button for my eth names that were auto migrated with `migrateAllLegacy`.

![return](https://user-images.githubusercontent.com/10460/75383942-20fad380-5892-11ea-9b3d-91c007873c68.png)

**Comment by akcryptoguy** [comment]
Agreed.  I was also looking for a return button today but I could not find it.  This is happening for me in Chrome with Metamask.  The other commands confirm that I am the owner but there is no release or return button.

![image](https://user-images.githubusercontent.com/45030509/75410305-63182980-5913-11ea-88bc-50c45519930b.png)

**Comment by Arachnid** [comment]
Fixed now!

**Comment by jefflau** [comment]
@ttdonovan Did it work for you?

**Comment by CoraCapuyan** [comment]
How to access?

**Comment by ttdonovan** [comment]
Yes this working for me. You must use unlock the account with the deposited ETH in MetaMask before clicking the "Return" button. I can confirm that I have recovered my deposited ETH with this button.
