### ISSUE TITLE
Issue with .onion resolution on v3 addresses

### ISSUE THREAD

**Issue by wschwab** [ensdomains/ens-app#623]
Hi all!

It seems to me that there is a problem with resolving v3 (super long 56 character) .onion content pieces. Casual research shows that not only my personal attempt is failing, but also the CIA [ENS-provided](https://medium.com/the-ethereum-name-service/list-of-ens-names-that-resolve-to-tor-onion-websites-99140a4c674f) [Tor link](https://app.ens.domains/name/ciagovtor.eth) fails. A quick look shows that when ENS tries to resolve the address, it appends `https://` to it. (You can reproduce this by clicking on the link in the ENS app on the CIA ENS page linked above.) 

It does not do this for the simpler v2 addresses. ([Here](https://app.ens.domains/name/duckduckgotor.eth)'s an example.)

I'm not sure where in the coed to find this. I thought this line might be the culprit (from [/src/componenents/Links/ContentHashLink.js](https://github.com/ensdomains/ens-app/blob/dev/src/components/Links/ContentHashLink.js):
```
} else if (protocolType === 'onion' || protocolType === 'onion3') {
    externalLink = `https://${decoded}.onion` <=================== THIS LINE
    url = `onion://${decoded}`
  } else {
```
but I can't figure out why the v2 addresses are working, then. I'd love to do more and just throw up a PR, but I'm not figuring out what to change. (Maybe it's just the line above, and all that needs to be done is to take out the `https://`? I dunno.)

Cheers!

**Comment by wschwab** [comment]
I'm doing a bit of research, and I suspect just lowering `https://` to `http://` should fix the issue. I suspect the issue is that many hidden service (.onion) providers see TLS certs as at best redundant, and at worse damaging. For some reason, 

I have not yet encountered a single v3 address that supports TLS, and I wonder if there's something baked in to these addresses that causes them not to verify SSL certs. I'll throw in a couple of sources about not needing `https` on `.onion` sites:
https://security.stackexchange.com/questions/105646/is-it-safe-to-access-http-sites-from-tor
https://blog.torproject.org/facebook-hidden-services-and-https-certs (in section 4)

Based on all this, I'm going to try a PR just changing `https://` to `http://` in the line singled out above.

**Comment by brantlymillegan** [comment]
Thanks for catching and fixing this!
