### ISSUE TITLE
My Names list has duplicates

### ISSUE THREAD

**Issue by MicahZoltu** [ensdomains/ens-app#629]
https://app.ens.domains/address/0x12475b855a2aeac5d07ec882c85f15d4d91af445
![image](https://user-images.githubusercontent.com/886059/76915681-1c599600-68f9-11ea-9ac0-8877cf063568.png)

Note that every name in that list shows up twice in the list except the subdomain.

**Comment by brantlymillegan** [comment]
I have the same problem on my list of names as well

**Comment by brantlymillegan** [comment]
This is due to this page displaying names that you are the Registrant for and names you are the Controller for (so names are getting displayed twice). We will be separating these out into two separate tabs soon which will fix this problem @MicahZoltu
