### ISSUE TITLE
Implement ability to set multiple records in one txn

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#644]
Users should be able to set multiple Other Addresses records, their Content record, and multiple Text Records all in one txn. This would make setting up the records for a new ENS name much easier. It would also make ENS more txn efficient.

**Comment by jefflau** [comment]
- [ ] Refactor all recordItems to use them same tx signature and use the multiCall functionality on the new resolver.

- [ ] Old functionality should probably be preserved for old resolver.

- [ ] Get all records before the RecordsAndResolver component so we can create an object that be compared to the records that need to be updated. This will be to show UI changes

- [ ] Check there are any records that have been updated before sending a tx

- [ ] Refactor old migrate resolver function to reuse with this component

- [ ] Allow refetch to work with all items
