### ISSUE TITLE
[unknownasd123].eth cannot be renewed

### ISSUE THREAD

**Issue by daimesava** [ensdomains/ens-app#648]
Similar to #628 but in my case the domain doesn't display when clicked on:

![Screen Shot 2020-03-27 at 21 07 34](https://user-images.githubusercontent.com/56128157/77792351-e773de80-7070-11ea-976f-b149fe8c927c.png)

The bigger issue is that renew doesn't work for the 3 unknown domains. The confirmation popup appears, but after I click on *confirm* nothing happens and no metamask prompts. I know the issue isn't with MM because 2 other domains, which display correctly, were successfully renewed at the same time.

**Comment by brantlymillegan** [comment]
Do you know what these names are? If so, you can search for them directly in the search box, and then you should be able to go to a page with the name on it and renew it.

**Comment by daimesava** [comment]
That worked. Thanks!
