### ISSUE TITLE
Creating subdomain does not always refresh the list of subdomains

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#68]
After a new subdomain is created, it always add the newly created subdomain if tested locally using ganache. However, when I tested on Ropsten, it does not add the latest all the time (tested on Brave).

**Comment by chris-remus** [comment]
Could you please add a screen capture or screenshots @makoto?

**Comment by makoto** [comment]
I don't think there is much point pasting screenshot. It's newly created item not being refreshed to the list of subdomains. I suggest you try to create multiple subdomains and see that happens to you.
