### ISSUE TITLE
"Bin" button does not delete anything

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#69]
Pressing the "Bin" button does not do anything.
Looks like deleting content/address are not implemented yet.
![screen shot 2018-12-28 at 15 11 05](https://user-images.githubusercontent.com/2630/50506213-d4abdc00-0ab2-11e9-8000-aa3401d9f078.png)

**Comment by chris-remus** [comment]
Thanks for catching this @makoto Is it something you can fix in @jefflau's absence?

**Comment by makoto** [comment]
It's ready implemented at

**Comment by jefflau** [comment]
Should we close this as it seems to be implemented?
