### ISSUE TITLE
Support re-detection of injected provider.

### ISSUE THREAD

**Issue by MicahZoltu** [ensdomains/ens-app#702]
I'm building a Web3 provider and for privacy reasons it does not get injected into the page until the user explicitly says so.  This means that when the page is first loaded, `window.ethereum` will be undefined.  Then sometime later (user interaction) `window.ethereum` will become defined.  At this point in time, the ENS app needs to re-detect the attached provider but at the moment it doesn't.

Option 1: Poll `window.ethereum` periodically to see if it shows up.
Option 2: When the user clicks the "No Accounts" button, instead of just giving instructions also check `window.ethereum` again to see if it is now available.

**Comment by Devilla** [comment]
Is it resolved yet?

**Comment by makoto** [comment]
We will handle as part of other wallet integration as it needs to similar functionality to switch wallets.

**Comment by Devilla** [comment]
@makoto That's great. Thanks for the update.
