### ISSUE TITLE
Fix production source maps.

### ISSUE THREAD

**Issue by MicahZoltu** [ensdomains/ens-app#704]
I just spent the better part of a day debugging app.ens.domains because it was failing to load for me because source maps are not setup correctly (possible not setup at all?).  If source maps had been working correctly, I probably could have found the problem in a few minutes.  Next time, chances are I won't bother spending the time and instead you'll just end up with a production bug for some unknown amount of time until a developer can reproduce it and debug it some other way.

Pro Tip: Source maps don't take up any meaningful extra runtime space for users who don't open browser dev tools and when available they make debugging production problems *way* easier.  All you have to do (usually) is tell your bundler to include them and simply *not* delete them when you deploy to production.

**Comment by jefflau** [comment]
I'll look into it! Thanks for the support

**Comment by RONIZAM80** [comment]
How

**Comment by jefflau** [comment]
> I just spent the better part of a day debugging app.ens.domains because it was failing to load for me because source maps are not setup correctly (possible not setup at all?). If source maps had been working correctly, I probably could have found the problem in a few minutes. Next time, chances are I won't bother spending the time and instead you'll just end up with a production bug for some unknown amount of time until a developer can reproduce it and debug it some other way.
> 
> Pro Tip: Source maps don't take up any meaningful extra runtime space for users who don't open browser dev tools and when available they make debugging production problems _way_ easier. All you have to do (usually) is tell your bundler to include them and simply _not_ delete them when you deploy to production.

I'm looking into this now. Seems to have been setup correctly for me. Can you elaborate on how they don't work if they still don't work for you?

<img width="819" alt="Screenshot 2020-05-26 at 13 41 52" src="https://user-images.githubusercontent.com/1221141/82864240-b459a880-9f56-11ea-908f-722b61975977.png">

**Comment by MicahZoltu** [comment]
It appears to be working for me now.  Will close.  Thanks!
