### ISSUE TITLE
Cant migrate adrianwoodward.eth 

### ISSUE THREAD

**Issue by AdrianWoodward** [ensdomains/ens-app#714]
Cant migrate adrianwoodward.eth   logged in with metamask, migrate is grey please resolve or advise as to the require action.

**Comment by jefflau** [comment]
Can you make sure the address of the controller matches the address on the left hand side in the sidenav?

**Comment by jefflau** [comment]
I'm assuming this has been resolved. Please reopen if you still have an issue

**Comment by AdrianWoodward** [comment]
Resolved thanks
