### ISSUE TITLE
USD estimater not working in bulk renewals tool on My Names page

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#718]
It estimates the USD value of the ETH to be $0

<img width="1792" alt="Screen Shot 2020-05-05 at 10 45 19 AM" src="https://user-images.githubusercontent.com/30162762/81098262-fd6d8e00-8ebd-11ea-8936-2825fe6a9af2.png">

**Comment by jefflau** [comment]
Are you using Brave? I think this happens when Brave blocks external API requests, for some reason it thinks etherscan is a tracker. Works for me in Chrome. I'll change this to "if I don't get anything back from Brave, don't show an estimate at all"

**Comment by brantlymillegan** [comment]
No, this was in Chrome. The estimator works for me on the normal name page,
but not on the bulk renewal page.
