### ISSUE TITLE
Mobile App Display Sizing Optimization

### ISSUE THREAD

**Issue by chris-remus** [ensdomains/ens-app#72]
Tested on Status iOS browser v0.9.30 (11274); node 0.16.3

Mobile app screens are slightly too wide to fit screen when first loaded. Upon returning to the same page in the same browser session, screen width fits screen well.

See [screen capture here](https://drive.google.com/file/d/1cPFdSEpC4rSZ5PlqLKCXD8MbJoA-0njs/view?usp=sharing).

**Comment by jefflau** [comment]
Closing. Reopen if this is still occuring
