### ISSUE TITLE
Visiting sea.eth in the ENS portal errors out

### ISSUE THREAD

**Issue by dfinzer** [ensdomains/ens-app#721]
https://app.ens.domains/name/sea.eth is broken

Seems to happen from any account, web3 enabled and disabled.

![image](https://user-images.githubusercontent.com/613881/81132071-fec0aa00-8f01-11ea-8bd5-3e5c22da8305.png)

**Comment by jefflau** [comment]
Thanks for this. Pushing a fix now

**Comment by jefflau** [comment]
Should be fixed now
