### ISSUE TITLE
Note explaining that renewing a name you don't own will not get you the name if/when it lapses

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#734]

**Comment by makoto** [comment]
@brantlymillegan @rliebert90 Hover over does not work from mobile, so I suggest coming up with different solution.

**Comment by brantlymillegan** [comment]
@makoto Then how about a note that appears under the Renew button if you aren't the Registrant or Controller that reads
"Note: Renewing a name you do not own does not give you ownership of it."

We need to get something added quickly because people are actively making this mistake right now

**Comment by rliebert90** [comment]
@brantlymillegan what happens now when someone tries to renew a name they don't own? 

@makoto can we detect when this is happening (someone trying to renew a name that isn't theirs) and show this message only when that happens? If they click renew, they'll see this red text: 

<img width="942" alt="Screen Shot 2020-05-12 at 12 39 58 PM" src="https://user-images.githubusercontent.com/45074845/81721738-586b2c00-944e-11ea-849f-1ab7f6c4368a.png">

**Comment by brantlymillegan** [comment]
@rliebert90 this looks great. Right now, any Ethereum account can pay to renew any name. So if you renew a name you don't own, you're just adding to the registration time of the name for the other person. (This is useful for certain scenarios.)

So this should be shown prior to the person clicking the Renew button, but should maybe just be shown automatically when a person has the renewal tool open on a name they don't own.
