### ISSUE TITLE
Implement new design of Content record and upload tool

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#766]

**Comment by rliebert90** [comment]
@jefflau and @brantlymillegan see annotated pdf for new designs. I have a question about this issue (view in Adobe reader to see contextual comments/questions).

[ENS_Name-Detail_Content-record.pdf](https://github.com/ensdomains/ens-app/files/5907777/ENS_Name-Detail_Content-record.pdf)
