### ISSUE TITLE
Deal with avatars that are not 1 x 1 aspect ratio 

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#771]

**Comment by makoto** [comment]
@brantlymillegan @jefflau 

If I remove equal height to width, it will no longer squash but still looks strange

<img width="765" alt="Screenshot 2020-05-25 at 15 51 59" src="https://user-images.githubusercontent.com/2630/82823650-de03c880-9e9f-11ea-9cb3-545971578ffd.png">

I suggest that we just get rid of rounding altogether. Looks still bad if extremely wide, but people should be just aware that we don't shrink nor crop automatically.

square looks ok.

<img width="748" alt="Screenshot 2020-05-25 at 15 55 30" src="https://user-images.githubusercontent.com/2630/82823909-4b175e00-9ea0-11ea-878b-da2a605f0748.png">


<img width="745" alt="Screenshot 2020-05-25 at 16 08 05" src="https://user-images.githubusercontent.com/2630/82824870-0987b280-9ea2-11ea-90e3-912fe8e664ae.png">

**Comment by brantlymillegan** [comment]
I liked the circle like you had it, and I think a circle is how it's likely going to be implemented in most places. Maybe we should wait until we have an avatar standards doc before we implement this.

**Comment by makoto** [comment]
It's actually already merged into master a week ago. If you want to display round image, you can still do so by uploading round image.
