### ISSUE TITLE
Show expiration / end of grace period on Favourites list

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#772]

**Comment by makoto** [comment]
working on it with https://github.com/ensdomains/ens-app/pull/785

**Comment by makoto** [comment]
https://github.com/ensdomains/ens-app/pull/785

**Comment by brantlymillegan** [comment]
<img width="1792" alt="Screen Shot 2020-06-01 at 2 44 55 PM" src="https://user-images.githubusercontent.com/30162762/83458284-20388700-a417-11ea-9895-d310c0259df4.png">
<img width="1792" alt="Screen Shot 2020-06-01 at 2 45 02 PM" src="https://user-images.githubusercontent.com/30162762/83458294-229ae100-a417-11ea-9fbe-3a4c15a06353.png">

Looks likes the expiration/grace period notice is bolded on Favourites but not on My Names, both should be not bolded.
