### ISSUE TITLE
"Return" button is visible to non registrant

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#788]
Example: https://app.ens.domains/name/cointelegraph.eth

<img width="1000" alt="Screenshot 2020-06-01 at 17 40 11" src="https://user-images.githubusercontent.com/2630/83431359-20dd1780-a42f-11ea-88fd-dd07a9f60579.png">

**Comment by brantlymillegan** [comment]
Be sure to be clickable for owner of the name in the old registry, not currently, Otherwise, greyed out.
