### ISSUE TITLE
Add confirmation box when updating resolver with some extra warning message.

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app#79]
Currently confirmation box comes up only when transferring the contract ownership. The same popup should exist when updating resolver but with extra sentence such as `Changing the resolver will affect all the associated records too`

**Comment by makoto** [comment]
This came up while discussing UX on updating resolver with Becca

**Comment by jefflau** [comment]
Is this complete already @makoto?

**Comment by jefflau** [comment]
Closing. Reopen if not
