### ISSUE TITLE
There are components not included in the translation.

### ISSUE THREAD

**Issue by YutaSugimura** [ensdomains/ens-app#809]
![スクリーンショット 2020-06-10 3 33 03](https://user-images.githubusercontent.com/44302124/84187834-97cc7d00-aacd-11ea-9464-14ed82cd1c99.png)

The text is not translated.

**Comment by brantlymillegan** [comment]
@jefflau Looks like this line "This name is already registered" simply isn't on the language JSON files (neither English or other languages). Let me when when it's added so I can coordinate with the translations.

**Comment by brantlymillegan** [comment]
PR to fix just this one missing phrase from the JSON files [#810](https://github.com/ensdomains/ens-app/pull/810)

**Comment by brantlymillegan** [comment]
Closing this since this we now have issue 812 for this and other places not available for translation https://github.com/ensdomains/ens-app/issues/812
