### ISSUE TITLE
Update English language JSON file to contain all needed copy (because it is used to translate to other languages)

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#812]
**Important: Whenever a new line is added to the json file, please let me know so that I can add it to my translation spreadsheet.**

**Comment by brantlymillegan** [comment]
One example of copy not in the language json file has [already been identified](https://github.com/ensdomains/ens-app/issues/809). Before we implement more language, someone needs to go through the Manager again (maybe with a language other than English selected) and identify any copy that isn't a part of the language JSON file, and then update the [English JSON file](https://github.com/ensdomains/ens-app/blob/dev/public/locales/en.json) to include it. The English JSON file is used as the basis for translations into other languages.

**Comment by YutaSugimura** [comment]
I found some of these on the domain details page.

![スクリーンショット 2020-06-10 9 52 01](https://user-images.githubusercontent.com/44302124/84215228-98323b80-ab00-11ea-849c-3273b53cf6c9.png)
[domain details page](https://app.ens.domains/name/sugimura.eth/details)

In order from top to bottom.
* Registrant
* REGISTRATION DATE
* RESOLVER
* Migrate
* You’re using an outdated version of the public resolver, Click to migrate your resolver and records. You will need to confirm two transactions in order to migrate both your records and resolver.
* To reset your resolver manually, click set and enter the address of your custom resolver.
* You can’t edit or add records until you migrate to the new resolver.

There could be more.

**Comment by brantlymillegan** [comment]
PR to fix this [#810](https://github.com/ensdomains/ens-app/pull/810)

**Comment by YutaSugimura** [comment]
The untranslated part

The items you checked are the modifications to the pull request.

## /search/DOMAIN
- [x] Search Results Title (text: Top Level Domains)
- [x] domain state (text: available / auction / default / owned / owner)

## /address/ADDRESS
### /registrant
- [ ] message (text: This address does not own any domains)

### /controller
- [ ] message (text: This address does not own any domains)

## /name/DOMAIN
- [x] owner type (text: Registrant / Controller)

### /register
- [x] unit of years

### /details
- [x] registration date

#### * Resolver
- [ ] input placeholder
- [x] Use Public Resolver Button
- [x] save button

##### Modal Component
- [x] title
- [x] description
- [x] previous
- [x] future
- [x] cancel Button
- [x] confirm Button

#####  Warning Component
- [x] title
- [x] migrate button
- [x] explanation of the warning
- [x] supplementary message

#### * Records
- [x] form title
- [ ] select list
- [ ] Input placeholder
- [x] save button

#####  Warning
- [x] explanation of the warning

##### ADDRESS
- [ ] input placeholder
- [x] save button

###### Reverse record
- [x] state name
- [x] description
- [ ] save button

##### OTHER ADDRESSES
- [ ] input placeholder
- [x] save button

There may be parts of it we haven't found yet.

**Comment by brantlymillegan** [comment]
@YutaSugimura Thank you very much! This gets a lot of the missing ones, will try to get this merged soon.

There are still a few here and there that aren't in the translation json yet, so this issue is still open.

I'll note that some of the missing translation I mentioned in my earlier comment are still not in the translation json file:

- On a DNS name page (e.g. see brantly.xyz): C.CONTROLLER, DNS OWNER, Sync, Refresh, the note about clicking refresh
- TLD not supported warning (when you search for a DNS name we don't support)

**Comment by YutaSugimura** [comment]
> * On a DNS name page (e.g. see brantly.xyz): C.CONTROLLER, DNS OWNER, Sync, Refresh, the note about clicking refresh

I've just fixed this problem.

@brantlymillegan Thank you.
Added a few more lines to the json file. Please add them to the spreadsheet.

**Comment by brantlymillegan** [comment]
@YutaSugimura thanks!
