### ISSUE TITLE
Favorite names from search results is broken

### ISSUE THREAD

**Issue by tabcat** [ensdomains/ens-app#823]
when searching without an extention a list component shows the matching names with their extention, currently only .eth. theres a favorite icon on the list items you should be able to click but mousing over to click the list item removes the favorite icon and replaces it with 'available' or 'unavalaible'.

![Screenshot from 2020-06-11 19-33-02](https://user-images.githubusercontent.com/36933094/84452231-e3d90800-ac1a-11ea-892f-e0990b9fcfe4.png)

![Screenshot from 2020-06-11 19-33-11](https://user-images.githubusercontent.com/36933094/84452235-e63b6200-ac1a-11ea-9521-df0d03837cc3.png)

**Comment by brantlymillegan** [comment]
I've checked this and it does this even if you are signed in to an Ethereum account. Added to our backlog to fix, thanks!
