### ISSUE TITLE
Use Chinese version of Etherscan when Chinese language is used

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#828]
From Liu Benben fro ENSUser (who provided our Chinese translation):

"[F]or Chinese users, there is a problem. For some reason, we can't easily visit https://etherscan.io , which causes the user to be unable to access when clicking "view on Etherscan". In our own modified version, use the official Chinese version of ethersan（ https://cn.etherscan.com/ ）Replaced the general version（ https://etherscan.io/ ）。

Therefore, I have a suggestion to add a judgment to the ENS APP. If the user selects simplified Chinese, the app will provide them with https://cn.etherscan.com/ related links. However, only the transformation of the main network can be provided, because there is no corresponding Chinese version of Etherscan for the test web browsers such as ropsten."

**Comment by jefflau** [comment]
Sounds fine to me, although i went to cn.etherscan.com, it looks exactly the same. Is it just because of the great fire wall or because of language?

**Comment by jefflau** [comment]
I would also make this way lower priority as chinese users should be able to manually add cn in the meantime

**Comment by makoto** [comment]
Does this site supports testnet like rinkeby, ropsten, and goerli?

**Comment by brantlymillegan** [comment]
> Does this site supports testnet like rinkeby, ropsten, and goerli?

I don't think so
