### ISSUE TITLE
Usability issue - small confusion on 'outdated resolver' issue

### ISSUE THREAD

**Issue by tjayrush** [ensdomains/ens-app#835]
I had a number of .eth domains with resolvers set up quite some time ago (like when ENS first came out). Today, I went to review my ENS names, and when I look at each name in the `apps.ens.domains/names` page, it says and I quote,

>> You’re using an outdated version of the public resolver, Click to migrate your
>> resolver and records. You will need to confirm two transactions in order to
>> migrate both your records and resolver.

This was quite confusing because (1) I don't have 'records' for any of my domains, and (2) because I have no records, I only had to send one transaction to migrate to the new resolver for each domain.

I was worried each time I sent a transaction to migrate that I was doing something wrong.

Very simple suggestion: Do not say I will have to make two transactions. Say something like "You will need to confirm at least one transaction (and possibly two if there are 'records' associated with the resolver)  to complete the migration."

Something like that in order to remove the 'fear' associated with only doing one transaction.

**Comment by brantlymillegan** [comment]
Thanks for the tip! We'll take that into consideration
