### ISSUE TITLE
Investigate creating a settings page

### ISSUE THREAD

**Issue by jefflau** [ensdomains/ens-app#85]
Had discussions with @Arachnid about adding enjinx as a block explorer option so the user can choose between etherscan or enjinx. This raises the question - how do we store this data? The most direct and obvious is to have it in localStorage. Currently we do not store anything apart from favourites in local storage. For the permanent registrar we will likely need to store reveal details that we send on behalf of the user. Therefore we should spend some time investigating and researching how we should best architect this solution. The solution I expect will be client-side only at first, then we will be able to sync to a centralised back-end or storage solution of some sort in the future (IPFS/Swarm)

**Comment by brantlymillegan** [comment]
Interesting idea. I'm trying to think of what else would go on a settings page other than choosing your preferred block explorer.
