### ISSUE TITLE
Do not offer to replace content-hash when no change

### ISSUE THREAD

**Issue by ligi** [ensdomains/ens-app#868]
Better would be a message like "Contenthash already set to: XX". This can prevent unnecessary transactions on chain.
![Selection_093](https://user-images.githubusercontent.com/111600/88010816-0dd4f280-cb16-11ea-9c65-28019556be09.png)

**Comment by makoto** [comment]
Even though it's slightly more user friendly, not sure if it's worth fixing (as it is pretty obvious that it's trying to set to the same thing). I also do that just to test I can make transaction without actually changing the content so prefer to keep it, too.

**Comment by LeonmanRolls** [comment]
Closing as there isn't much desire to implement this
