### ISSUE TITLE
Support looking up TLDs and the root

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#87]
As a general purpose tool, I should be able to look up 'eth' and get the page describing it. From there it should be possible to  look at  'parent domain' and examine the root, too.

**Comment by jefflau** [comment]
I think this will be more easily implemented if we get rid of the 'all search' bar. Initially we had it designed to allow anyone to search subdomains at the same time. So for instance, if I searched 'bert', it would give me all the subdomains i can register that are available with bert as the label. But obviously the problem with search any root domains is that they could also be a subdomain. Myself and Becca discussed that maybe we should remove this as we currently don't use the subdomain registrar to actually register domains and it would be possible to add this functionality without confusion

**Comment by Arachnid** [comment]
How would you readd it when needed without introducing the same problem again? Bearing in mind that we'll offer registration under .ETH really soon now, too!

**Comment by jefflau** [comment]
I think we should split it up so we have a separate page for searching/registering subdomains and keep the main search for searching for full names and/or top level domains

**Comment by jefflau** [comment]
FYI, you can still get this to work if you go to /name/eth. Or you can click the parent link from a second level domain and look at eth. But yeah until I remove the subdomain registrar search, this won't work from the search bar.

**Comment by Arachnid** [comment]
> I think we should split it up so we have a separate page for searching/registering subdomains and keep the main search for searching for full names and/or top level domains

Yup, fair enough.

> FYI, you can still get this to work if you go to /name/eth. Or you can click the parent link from a second level domain and look at eth. But yeah until I remove the subdomain registrar search, this won't work from the search bar.

True! It's not possible to look up the root, though.

**Comment by jefflau** [comment]
Partially addressed in https://github.com/ensdomains/ens-app/pull/99

**Comment by brantlymillegan** [comment]
Noting here that when I go to the page for "ETH" (the TLD) and click "Subdomains", the page just goes completely blank for me. This does not happen when I try this for other TLDs, like .KRED and .LUXE.

Also, while we do have some TLD support, I'm not aware of a page for the root (which would presumably show all of the TLDs as "subdomains".

**Comment by makoto** [comment]
`Noting here that when I go to the page for "ETH" (the TLD) and click "Subdomains", the page just goes completely blank for me.` this looks like a bug which I can fix.

In terms of `root`, how do we want to represent @Arachnid ? `.` is not supported as it represents delimiter. Do we treat `name/root` as a root domain (and hope ICANN never adds `.root` as tld?)

**Comment by makoto** [comment]
Update: I will use `/name/[root]` to represent root domain.
