### ISSUE TITLE
Update Manager with new Text Records standards

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#872]

**Comment by brantlymillegan** [comment]
See discussion starting [here](https://github.com/ethereum/EIPs/issues/2439#issuecomment-663807627). Vendor keys are changing to their website, backwards. So, e.g., vnd.twitter will should become com.twitter.

**Comment by ricmoo** [comment]
Just checking on why this issue was closed? It seems like it should maybe be re-opened? The [EIP](https://eips.ethereum.org/EIPS/eip-634) has been updated. :)

**Comment by MikeD123** [comment]
Are you guys going to add the ability to set the public key on the manager page?

https://docs.ens.domains/contract-api-reference/publicresolver#set-public-key

I can't see where I can set it on the manager app, if it's not available, are you guys planning on ever providing that on the site?

Thanks so much!
