### ISSUE TITLE
Support search API

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#88]
The app should  support the 'tab to search' facilities used for the Chrome address bar.

**Comment by jefflau** [comment]
What do you mean by 'tab to search'?

**Comment by Arachnid** [comment]
If you use a site like Google or Wikipedia, you can enter part of the site name until your browser autofills the rest, then press tab to get a dialog that lets you use that site's search functionality right from the address bar.

**Comment by Arachnid** [comment]
Here's the spec: https://developer.mozilla.org/en-US/docs/Web/OpenSearch
