### ISSUE TITLE
Expand number of cryptocurrencies the Manager supports

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#881]

**Comment by brantlymillegan** [comment]
There are a number of top cryptocurrencies we don't support in our Manager that we need to support, such as:

- ADA
- BSV
- XTZ
- XMR
- NEO
- ERD
- ALGO
- QTUM
- HBAR
- ICX
- ZIL

**Comment by makoto** [comment]
Just checked cointypes at https://github.com/satoshilabs/slips/blob/master/slip-0044.md
## cointypes

ADA  = 1815
BSV = 236
XTZ = 1729
XMR = 128
VET = 818
NEO = 888
ERD = 508
ALGO = 283
QTUM = 2301
HBAR (XHB) = 3030
ICX = 74
ZIL = 313
FLOW = 539
NEAR = 397

**Comment by makoto** [comment]
And some notes on format
- ADA = [bech32 is the recommended option](https://docs.cardano.org/projects/cardano-serialization-lib/en/latest/rust/chain-libs/chain-impl-mockchain/doc/address.html?highlight=bech32)
- BSV = can'f find developer doc at https://bitcoinsv.io/
- XTZ = couldn't find at https://tezos.gitlab.io/ 
- XMR = cound't find at https://www.getmonero.org/resources/developer-guides/wallet-rpc.html
- VET = cound't find at https://doc.vechainworld.io/
- NEO = couldn't find at https://docs.neo.org/
- ERD = [bech32](https://docs.elrond.com/tools/rest-api-overview/addresses#get-address)? 
- ALGO = [Ed25519?](https://developer.algorand.org/docs/features/accounts/?query=create%2520account#keys-and-addresses)
- QTUM=["legacy", "p2sh-segwit" or "bech32"](https://docs.qtum.site/en/commands/#getnewaddress--account-addresstype-)
- HBAR = [ed25519?](https://docs.hedera.com/guides/core-concepts/accounts)
- ICX = Couldn't find at https://www.icondev.io/docs
- ZIL = [bech32?](https://zilpay.xyz/Documentation/zilliqa-api-crypto/#window-zilpay-crypto)
- `FLOW` uses 16 hex with some [checksum](https://github.com/onflow/flow-go-sdk/blob/master/address.go#L238)
- NEAR = [string = they have their own name service as part of the protocol](https://nomicon.io/DataStructures/Account.html#account-id)

**Comment by brantlymillegan** [comment]
> * NEAR = [string = they have their own name service as part of the protocol](https://nomicon.io/DataStructures/Account.html#account-id)

Yes, but we should still support it

**Comment by brantlymillegan** [comment]
Additional ones:

- FIL
- AVA

**Comment by brantlymillegan** [comment]
I just got off a call with Gemini, and they are interested in various kinds of integration with ENS. One thing they pointed out is that we support in our Manager all the cryptocurrencies they do except for ZEC. To show good will to Gemini, @makoto could you prioritize trying to get ZEC address support in the Manager ASAP?

**Comment by makoto** [comment]
@brantlymillegan can you check with Gemini if they are okay with just storing transparent address, not shielded address?

There is outstanding PR on ZCASH but @Arachnid commented the need to support shielded address.

https://github.com/ensdomains/address-encoder/pull/10

I spoke to Trust wallet team who already support zcash but they [also only support transparent address](https://github.com/trustwallet/ens-coincodec/blob/master/zcash_test.go).

**Comment by brantlymillegan** [comment]
> @brantlymillegan can you check with Gemini if they are okay with just storing transparent address, not shielded address?
> 
> There is outstanding PR on ZCASH but @Arachnid commented the need to support shielded address.
> 
> [ensdomains/address-encoder#10](https://github.com/ensdomains/address-encoder/pull/10)
> 
> I spoke to Trust wallet team who already support zcash but they [also only support transparent address](https://github.com/trustwallet/ens-coincodec/blob/master/zcash_test.go).

But don't we want to support both transparent and shielded addresses? Is it a lot harder to support both? And if we support transparent addresses right now, can we easily add support for shielded addresses later?

**Comment by makoto** [comment]
I don't know zcash well but not sure if you want to store shielded address (which suppose to be secret) into a publicly accessible place. I also don't know how hard to implement support for the shielded address tbh.

**Comment by makoto** [comment]
In terms of supporting transparent address, the PR I showed above is a bit out of date (people did some optimisation refactoring), so I tried to implement myself as follows but the testing isn't passing. Am I wrong to understand that `0xb8` and `0xbd` are the version number? What should I put instead if it's wrong?

<img width="701" alt="Screenshot 2020-08-19 at 19 14 20" src="https://user-images.githubusercontent.com/2630/90673967-605a1980-e250-11ea-8816-f30c0dab7b13.png">

<img width="776" alt="Screenshot 2020-08-19 at 19 12 57" src="https://user-images.githubusercontent.com/2630/90673989-67812780-e250-11ea-9868-9e736efccb6a.png">

**Comment by brantlymillegan** [comment]
@makoto Just talked to Nick. He said it'd be great if we could add support for both at the same time. But if we can't do that and we only add support for transparent addresses, that's fine as long as the encoding makes it clear people can distinguish between them. To determine that we probably just need to talk to a Zcash dev (otherwise it could take us a long time to try to figure out on our own).

**Comment by makoto** [comment]
@Arachnid could you review https://github.com/ensdomains/address-encoder/pull/45 . Also we should pay bounty to the guy who originally submitted https://github.com/ensdomains/address-encoder/pull/10 as it's mostly his code

**Comment by makoto** [comment]
@Arachnid this one is also good to go for Tezos https://github.com/ensdomains/address-encoder/pull/46 . In terms of your earlier comment about the pr17, I commented [here](https://github.com/ensdomains/address-encoder/pull/17#discussion_r475886173).

NOTE: I noticed that TrustWallet encode/decode [differently](https://github.com/trustwallet/ens-coincodec/blob/master/tezos_test.go#L15 ) so I reported to the team.

**Comment by makoto** [comment]
@Arachnid can you also either merge or close https://github.com/ensdomains/address-encoder/pull/35 ? This could potentially impact other outstanding PRs

**Comment by makoto** [comment]
Also added DOT as it was super easy extension to KSM https://github.com/ensdomains/address-encoder/pull/47

**Comment by Arachnid** [comment]
@makoto Thanks! I left some comments on your PRs.

**Comment by brantlymillegan** [comment]
@makoto I've set up bounties for a bunch of these for the Apollo Gitcoin hackathon we were invited to, and I'm getting a lot of responses. So please check the outstanding PRs tab before doing the work to add a new cryptocurrency address
