### ISSUE TITLE
Return Button Visible but not Active

### ISSUE THREAD

**Issue by toddsampson** [ensdomains/ens-app#882]
I am hitting an issue when trying to recover deposited funds from a few domains I own. The Return button is visible, but it is grayed-out and not clickable.

All of the domains that I have that are working show my address for both the Registrant and Controller. The ones that aren't working show my address for the Registrant, but "0x0000000000000000000000000000000000000000" for the Controller.

I tried to set the controller to my address to see if that would fix the issue, but I get the following warnings/errors in Console and nothing happens:

WARNING: Multiple definitions for addr
WARNING: Multiple definitions for setAddr
WARNING: Multiple definitions for safeTransferFrom”
Multiple definitions for supportsInterface
Error getting permanent registrar entry Error: call exception...

Any ideas on how to fix this?

**Comment by toddsampson** [comment]
Per the request from @makoto in the name-registry gitter chat, here is one of the domains I was having the issue with: https://app.ens.domains/name/jordaan.eth

**Comment by makoto** [comment]
Hi, @toddsampson . I think I fixed the bug. Could you give a try? The previous code was showing claim button only when you were the owner of the domain. Now that it's expired and released you are no longer the owner. I changed to check the deed owner instead.

**Comment by toddsampson** [comment]
Thanks @makoto. We were able to do the return on Jordaan.eth, but now the other names that we couldn't return have disappeared from the Controller list. The full list was 20 pages before and now is only 18, and it looks like the ones that we couldn't return have disappeared. Is there a way to bring those back so we can go return all the ones that were blocked before?

**Comment by makoto** [comment]
`The full list was 20 pages before and now is only 18` I don't quite understand what you mean. Can you point me to the URL?

**Comment by makoto** [comment]
Ah, I know what you mean. You want to show the list of the released name so that you can still release names?

We will set up a different app which allows you to show all the names which you have deposit locked up.

**Comment by toddsampson** [comment]
That is exactly it @makoto. Let me know if there is a new ticket/project I should follow to know when I can check this out. Thanks again for your help.
