### ISSUE TITLE
New UI dedicated just to reclaiming old deposit making it really easy

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#887]

**Comment by makoto** [comment]
Done at  https://github.com/ensdomains/claim

**Comment by toddsampson** [comment]
Thanks for knocking this out! Should I use https://ensdomains.github.io/claim/ that is listed in the source code or will it be added to the main ens.domains site?

**Comment by brantlymillegan** [comment]
> Thanks for knocking this out! Should I use https://ensdomains.github.io/claim/ that is listed in the source code or will it be added to the main ens.domains site?

We will be adding this to the main ens.domains site soon.
