### ISSUE TITLE
Remove warnings about names lapsing

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#890]
Please remove the warning on the main app landing page and on the individual name pages about names expiring and lapsing out of their grace period, as we don't need them anymore.

![1](https://user-images.githubusercontent.com/30162762/89336067-ac507000-d64d-11ea-854e-341d755cac38.png)
![2](https://user-images.githubusercontent.com/30162762/89336075-af4b6080-d64d-11ea-838e-a307299b91ab.png)

**Comment by makoto** [comment]
There is actually another one which only appears if you have expiring names.

<img width="1159" alt="Screenshot 2020-08-05 at 10 22 07" src="https://user-images.githubusercontent.com/2630/89397456-c8b0e300-d707-11ea-82a3-10fa360cc3f8.png">

Which I will change as follows.

<img width="1176" alt="Screenshot 2020-08-05 at 10 22 42" src="https://user-images.githubusercontent.com/2630/89397321-a028e900-d707-11ea-8271-7b1390ca41fc.png">

**Comment by brantlymillegan** [comment]
> There is actually another one which only appears if you have expiring names.

Are you sure? It shows up for me when I look at a name page even if I'm not signed in with MetaMask. And if I am signed in to MetaMask, it still shows up for me even though I don't think I have any names expiring soon.
