### ISSUE TITLE
Add history of relevant transactions for names

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#906]

**Comment by rliebert90** [comment]
@jefflau and @brantlymillegan see annotated pdf for new designs (view in Adobe reader to see comments). I have a couple questions on these pages – feel free to comment answers here or message or email me: 

*Note - this pdf is the same as the pdf I uploaded for the github issue 'add WHOIS info'. 

[ENS_Name-Detail_Advanced-settings_WHOIS-History.pdf](https://github.com/ensdomains/ens-app/files/5907728/ENS_Name-Detail_Advanced-settings_WHOIS-History.pdf)
