### ISSUE TITLE
Add new WHOIS info

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#908]

**Comment by rliebert90** [comment]
@jefflau and @brantlymillegan see annotated pdf for new designs (view in Adobe reader to see comments). I have a couple questions on these pages – feel free to comment answers here or message or email me: 

[ENS_Name-Detail_Advanced-settings_WHOIS-History.pdf](https://github.com/ensdomains/ens-app/files/5907714/ENS_Name-Detail_Advanced-settings_WHOIS-History.pdf)

**Comment by A2be** [comment]
Two comments, one general, and one on the specifics of the design shown in the pdf added a few days ago.

On a general level, I strongly support the addition of a less-nerdy way for the general user of crypto to access the History of a particular ENS `ens_name.eth` via the ENS webapp.  Having a web2 method by which a non-nerd, say a public accountant doing tax work or an attorney/solicitor doing legal work, can access the historical information is a very good thing!

**Comment by A2be** [comment]
That said, the History desing shown in [(https://github.com/ensdomains/ens-app/files/5907714/ENS_Name-Detail_Advanced-settings_WHOIS-History.pdf)] remains a bit abstruse.

Might it be possible to show that History both in a technical way (like the current pdf) and also in a way with a better UX for the non-geek?  

Something like:

**Yourname.eth**                      ENS history as of 2021-02-06
            **Epoch                                                       Owner                                         ENS controller**
            2019-11-06 to present               0xa9261620b00ae2c2d25a8e80...          0xa9261620b00ae2c2ef94....
            2018-03-15 to 2019-11-062018-03-10 to 2018-03-15

**Comment by makoto** [comment]
Waiting for new design

**Comment by brantlymillegan** [comment]
Closing since this will be covered in the redesign
