### ISSUE TITLE
Ability to delete subdomains.

### ISSUE THREAD

**Issue by MicahZoltu** [ensdomains/ens-app#919]
**Is your feature request related to a problem? Please describe.**
I created a subdomain, and now want to delete it.

**Describe the solution you'd like**
A trash can button on the subdomain or on the subdomain list page that will do whatever is necessary to delete a subdomain.

**Describe alternatives you've considered**
Setting all subdomain values to `0` (like controller, resolver, records, etc.).  This doesn't work currently.

**Additional context**
It is possible that setting everything to `0` is "deleting" my subdomain but my browser is caching it or something?

**Comment by makoto** [comment]
Solved at https://github.com/ensdomains/ens-app/pull/925
