### ISSUE TITLE
Add new encoding library additions to Manager

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#932]
I'm keeping a running list of newly added coins to our encoding library that haven't been added to the Manager yet, and we can add them in a batch once we get a large enough number:

- HBAR
- QTUM
- HNS
- NMC
- ZEC
- DCR
- ONT
- ICX
- LSK
- STEEM
- HIVE
- ALGO (disabled for now?)
- EGLD
- BPS
- DIVI
- NANO
- LRG
- AIB
- RDD
- IOTX
- ONE
- ELA
- CCXX
- ARK
- CCA
- SYS

**Comment by makoto** [comment]
Umm, @Arachnid approved and merged master into the PR, but he didn't merge the PR back into master.
Is it mistake?

<img width="1375" alt="Screenshot 2020-09-24 at 11 42 41" src="https://user-images.githubusercontent.com/2630/94135265-238acf00-fe5b-11ea-9308-0060afe6b003.png">
