### ISSUE TITLE
Implement new UI for setting Public Resolver

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#946]

**Comment by rliebert90** [comment]
@jefflau I emailed you a file for this - let me know if you have any feedback or questions!

**Comment by rliebert90** [comment]
@jefflau and @brantlymillegan see annotated pdf for new designs (view in Adobe reader to see comments):

[ENS_Name-Detail_Public-resolver.pdf](https://github.com/ensdomains/ens-app/files/5907719/ENS_Name-Detail_Public-resolver.pdf)

**Comment by makoto** [comment]
Waiting for UI makeover

**Comment by brantlymillegan** [comment]
Closing since this will be covered in the redesign
