### ISSUE TITLE
Make look up of reverse resolution more useful

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#947]

**Comment by rliebert90** [comment]
@brantlymillegan can you clarify what you mean by this? Do you mean make the 'My Names' sidebar tab more useful than its current use of easy renewal for all the names associated to your address?

**Comment by brantlymillegan** [comment]
@rliebert90 We are referring to the fact that a person will be able to search for [Ethereum address].addr.reverse and see info about their reverse resolution record that way. Talk to Makoto or Jeff for more info.

**Comment by makoto** [comment]
I will close this as our address page shows that the reverse record is set
