### ISSUE TITLE
Redesign flow for setting reverse resolution (separate page?)

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#948]

**Comment by rliebert90** [comment]
@jefflau and @brantlymillegan see annotated pdf for new designs (view in Adobe reader to see comments):

[ENS_My-Account-updates.pdf](https://github.com/ensdomains/ens-app/files/5907656/ENS_My-Account-updates.pdf)

**Comment by makoto** [comment]
Closing this as we moved to account page. The better version will wait until we have UI make over
