### ISSUE TITLE
Failed transactions on the second step of registration aren't handled correctly

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/ens-app#949]
A user on Discord reports that when the second registration transaction fails (for example, due to the price of ether shifting and the funds being insufficient), the manager does not recognise this and remains stuck waiting for the second transaction to confirm. We should handle this gracefully by letting them submit the transaction again.

**Comment by makoto** [comment]
I actually tested but wasn't able to replicate the issue . I also checked the code and there isn't a logic to keep it pending at Step3 only if it returns failing transaction. 

Having said that I did find a bug which prevents cache to clear if people doesn't complete Step3 so I will fix that first and see if this same problem still occurs.

https://github.com/ensdomains/ens-app/issues/951

**Comment by makoto** [comment]
I think I fixed this so closing for now
