### ISSUE TITLE
A few things to fix with new "multiple records in 1 tx" feature

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#964]
First I want to say that overall the new design looks great. I think this is a big step forward for our Manager and is definitely the right direction. Thanks for all of your work on this!

I looked at the new feature today and saw I few bugs/things that need adjusting:

1) If a name doesn't have any records of the Addresses or Text Records types, the record type title doesn't show up. This isn't true for the Content record type - that title always shows up even if you don't have one. The record titles should always show up whether records exist for them or not.

Here's an example (millegan.eth):

<img width="1792" alt="Screen Shot 2020-10-29 at 3 47 00 PM" src="https://user-images.githubusercontent.com/30162762/97640475-6fa2d380-1a06-11eb-989c-e6e0b91e4da5.png">

2) For all record types, if you don't have the record, it says "Not set" in grey text (which is good!), except for the Content record type, which says "Content Hash not set" in black text, if it's a name I own (if it's a name I don't own, then it doesn't say anything, but it does have a "copy" button strangely). Can this be uniform? Meaning, if you don't have a Content record, it should say "Not set" in grey text, whether I own the name or not.

3) Can we put ETH at the top of the default Addresses list? And let's make the default list (in this order): ETH, BTC, LTC, DOGE

4) How hard would it be to have the cryptocurrency's logo appear next to (e.g. to the left of) its three-character abbreviation in the Addresses list? I'd be happy to assemble all of the logos.

5) Rather than have the single drop down at the top to add an Addresses record or Text Record that doesn't automatically have a field displayed, could a drop down and field be at the bottom of the Address list and the Text Records list? That way it's clear you can add more of each type than shown when you're editing the records. This would need a way to add more fields for adding even more new records too.

6) When I try to enter a Text Record into the default provided fields, it doesn't let me type anything. E.g., I click on the field for the Text Record key URL, the blinking text cursor is there, but when I type nothing happens. If I'm editing a text record that already exists, then my typing *does* work.

7) There's no upload button for empty Content records.

8) For a Content Record that does have a content hash, the upload button is pushed to the next line below it. (These last two might be fixed by a redesign of the UI around the Content record?)

9) We need to update or remove the "Learn how to manage your name." instructions at the top of name pages, as it is no longer accurate

**Comment by jefflau** [comment]
1) Fixed
2) Fixed
3) Fixed
4) Out of scope, let's discuss this later
5) Out of scope
6) Fixed
7) I'll remove the upload for now since I couldn't test it
8) Same as above
9) Out of scope, let's get this as a new ticket
