### ISSUE TITLE
Add a hover icon that explains what each thing is in the Manager

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#966]
I propose that next to every black font label in the Manager we have an icon of a "?" that if you tap on mobile or hover over with your mouse on desktop will display a short definition of what that thing is or what it does.

The labels that need this are: parent, registrant, controller, expiration date, resolver, addresses, content, and text records.

If we do this, I can supply the text.

**Comment by makoto** [comment]
Given we are planning for the UI make over, I will keep it as low priority

**Comment by brantlymillegan** [comment]
Closing since this will be covered in the redesign
