### ISSUE TITLE
When viewing a name I don't own that doesn't have a Content record, it doesn't say "Not set" and instead shows copy button

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#970]
Here's what I see when I look at the name "nick.eth" (which I don't own)

<img width="1792" alt="Screen Shot 2020-10-30 at 9 40 15 AM" src="https://user-images.githubusercontent.com/30162762/97732559-4df42b80-1a9c-11eb-9abd-d098e65a7e5f.png">

Here's another example of one I don't own, but instead of nothing it shows "0x000..." (lloydmillegan.eth)

<img width="1792" alt="Screen Shot 2020-10-30 at 9 42 30 AM" src="https://user-images.githubusercontent.com/30162762/97732803-af1bff00-1a9c-11eb-9267-9a4ea72144fc.png">

**Comment by jefflau** [comment]
I could not replicate the blank bug with nick.eth, it shows not set for me. I've fixed the other bug. Please open another ticket if it still is happening
