### ISSUE TITLE
Show small logo of cryptocurrency next to three-letter cryptocurrency abbreviation in Addresses records

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#971]
If we decide to do this, I'd be happy to assemble the logos.

**Comment by rliebert90** [comment]
@brantlymillegan and @jefflau on page 9 of this pdf you can see an example of how this would look: https://www.dropbox.com/s/36bfvck18yh0dmb/ENS_Multiple-Records_11.05.2020.pdf?dl=0

I think the logos clutter the UI, and because they're so small, I'd argue they aren't adding much.

**Comment by brantlymillegan** [comment]
Noting here that I emailed Becca and Jeff all the logos today
