### ISSUE TITLE
Re-add IPFS upload tool

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#972]
Will this be done with the re-design of setting the Content record?

Also, I thought we had agreed that we'd keep this in and just skip having a test for it.

**Comment by jefflau** [comment]
I don't have an automated test for it (we never did) and I couldn't actually get it to work in any way when manually testing. So removing it seemed the logical step given Temporal were being unresponsive. I'm not comfortable leaving something in that is not even testable manually.

**Comment by makoto** [comment]
Temporal suspended service until further notice https://twitter.com/Temporalcloud/status/1347452505341317120 . Had a chat with IPFS pinata guys but their resource is currently stretched to add it on their own
