### ISSUE TITLE
Adjust design of adding additional Addresses and Text Records records

### ISSUE THREAD

**Issue by brantlymillegan** [ensdomains/ens-app#973]
I propose: Rather than have the single drop down at the top to add an Addresses record or Text Record that doesn't automatically have a field displayed, could a drop down and field be at the bottom of the Address list and the Text Records list? That way it's clear you can add more of each type than shown when you're editing the records.

**Comment by rliebert90** [comment]
@brantlymillegan I think this is a good idea, and it was actually something I explored a while back. Here is a pdf of the UI for this idea (having the dropdowns and fields in each respective section). Take a look over this @brantlymillegan and @jefflau, and let me know your thoughts: https://www.dropbox.com/s/36bfvck18yh0dmb/ENS_Multiple-Records_11.05.2020.pdf?dl=0

I think Jeff has done a lot of good work here, and making these changes may require significant effort on his end. A simpler solution for more visibility, that wouldn't drastically change the behavior Jeff already developed, would be to always show the record dropdown and field, and change the 'add/edit records' UI to just 'edit records'. 

It would look like this - 
<img width="960" alt="Screen Shot 2020-11-05 at 16 20 09" src="https://user-images.githubusercontent.com/45074845/98323374-a4d79480-1fb7-11eb-83da-6d4bc9089a2c.png">

And this, if a user clicks 'Edit Records' - 
<img width="927" alt="Screen Shot 2020-11-05 at 22 37 56" src="https://user-images.githubusercontent.com/45074845/98323417-b882fb00-1fb7-11eb-962f-ca50ac26455f.png">
