### ISSUE TITLE
Support IPFS avatars

### ISSUE THREAD

**Issue by MicahZoltu** [ensdomains/ens-app#986]
**Is your feature request related to a problem? Please describe.**
My avatar is an `ipfs://` URL and it doesn't show up anywhere in the UI.

**Describe the solution you'd like**
When my avatar is an `ipfs://...` URL, the website will convert that to `https://<some-ipfs-gateway>/ipfs/...`.

**Describe alternatives you've considered**
I have IPFS Companion browser plugin which makes `ipfs://...` links in my address bar work.  Perhaps figure out if there is something that can be done to make `ipfs://...` links in an `<img src=...>` also work.

**Additional context**
I would like to be able to use IPFS everywhere and not have to have my registration entries tightly coupled with any centralized gateway service like ipfs.io.  If the ENS app is tightly coupled, that is fine, because other things that grab my Avatar can choose to use different gateways (thus offering censorship resistance).

**Comment by makoto** [comment]
`avatar` field is specified on https://eips.ethereum.org/EIPS/eip-634 as `a URL to an image used as an avatar or logo`, so I think the support for IPFS should be added on the EIP itself first. Also, it's probably better to support other decentralised file storage such as swarm , sia, etc (we do support swarm and onion on contentthash and sia is on PR)

**Comment by MicahZoltu** [comment]
> a URL to an image used as an avatar or logo, so I think the support for IPFS should be added on the EIP itself first.

`ipfs://<cid>` is a valid URL.  The issue here is just that the ENS app doesn't know how to fetch/render ipfs:// URLs, and it would be nice if someone tought it to, so we can better support censorship resistance.

> work around by specifying a url with ipfs gateway

This solution isn't censorship resistant.  To me it is like saying that content hash should really just be a DNS CNAME.  The idea is to make it so the system as a whole is resistant to censorship, which means supporting censorship resistant protocols whenever possible rather than pushing users into centralized protocols.

**Comment by Umiiii** [comment]
https://github.com/ensdomains/ens-app/pull/1329

I think this ticket should be closed?

**Comment by MicahZoltu** [comment]
I just tested the live version of the app and can verify that this has been implemented.  Thanks!
