### ISSUE TITLE
Unable to assign content hash (ipfs) to a subdomain

### ISSUE THREAD

**Issue by ghost** [ensdomains/ens-app#989]
**Describe the bug**
I have added a subdomain to a name. When I attempt to add a content type to the subdomain it fails, by not launching the Metamask modal.

**To Reproduce**

1. Go to subdomain screen.
2. Click on 'ADD/EDIT RECORD'
3. Scroll in drop down to 'CONTENT'
4. paste an ipfs:// content hash.
5. click the SAVE button.
6. Click 'Confirm Button'
7. Observe modal: "Are you sure you want to do this?
This action will modify the state of the blockchain."
8. Click 'Confirm' again.
9. No indication in the UI that this failed.

**Expected behavior**
The workflow should complete and launch the sign step with Metamask wallet.

**Screenshots**
Javascript console log:

​ i18next::backendConnector: loaded namespace translation for language en Object
​ i18next: languageChanged en
​ i18next: initialized Object
​ MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.
(anonymous) @ ​
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for safeTransferFrom
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for supportsInterface
​ Object
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
​ WARNING: Multiple definitions for setAddr
​ WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
AddRecord.js:409 true "inside save button"
AddRecord.js:244 Object
RecordsCheck.js:38 Object
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
inpage.js:1 MetaMask - RPC Error: execution reverted Object
(anonymous) @ inpage.js:1
ApolloError.ts:57 Uncaught (in promise) Error: Network error: execution reverted
    at new t (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at v (Observable.js:140)
    at _ (Observable.js:179)
    at e.value (Observable.js:240)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at v (Observable.js:140)
    at _ (Observable.js:179)
RecordsCheck.js:38 Object
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
inpage.js:1 MetaMask - RPC Error: execution reverted Object
(anonymous) @ inpage.js:1
ApolloError.ts:57 Uncaught (in promise) Error: Network error: execution reverted
    at new t (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at v (Observable.js:140)
    at _ (Observable.js:179)
    at e.value (Observable.js:240)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at v (Observable.js:140)
    at _ (Observable.js:179)
RecordsCheck.js:38 Object
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
inpage.js:1 MetaMask - RPC Error: execution reverted Object
(anonymous) @ inpage.js:1
ApolloError.ts:57 Uncaught (in promise) Error: Network error: execution reverted
    at new t (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at v (Observable.js:140)
    at _ (Observable.js:179)
    at e.value (Observable.js:240)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at v (Observable.js:140)
    at _ (Observable.js:179)
SubDomains.js:131 Unable to get subdomains from subgraph, falling back to web3  undefined
children @ SubDomains.js:131
AddRecord.js:409 true "inside save button"
AddRecord.js:244 ObjectnewValue: "ipfs://QmTaRSMfxokTEgvdDuq2GgT9hGyAGZ5gGrFdzP5QseQZAm"records: coins: (53) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]content: "0x0000000000000000000000000000000000000000"loading: falsetextRecords: (6) [{…}, {…}, {…}, {…}, {…}, {…}]__proto__: ObjectselectedKey: nullselectedRecord: {label: "Content", value: "content"}__proto__: Object
RecordsCheck.js:38 Objectcoins: []content: "ipfs://QmTaRSMfxokTEgvdDuq2GgT9hGyAGZ5gGrFdzP5QseQZAm"textRecords: []__proto__: Object
ethers.min.js:1 WARNING: Multiple definitions for addr
ethers.min.js:1 WARNING: Multiple definitions for setAddr
inpage.js:1 MetaMask - RPC Error: execution reverted Object
(anonymous) @ inpage.js:1
ApolloError.ts:57 Uncaught (in promise) Error: Network error: execution reverted
    at new t (ApolloError.ts:57)
    at Object.error (QueryManager.ts:256)
    at v (Observable.js:140)
    at _ (Observable.js:179)
    at e.value (Observable.js:240)
    at observables.ts:15
    at Set.forEach (<anonymous>)
    at Object.error (observables.ts:15)
    at v (Observable.js:140)
    at _ (Observable.js:179)
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/contentscript.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sourcemaps/inpage.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://iplppiggblloelhoglpmkmbinggcaaoc/app/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Desktop (please complete the following information):**

- OS: OSX 10.13.6
- Browser Brave
- Version  V1.17.73

**Additional context**
Transaction works on ens domains, just not sub-domains.

**Comment by acegilz** [comment]
+1

It's not possible to update subdomain entries at all, I have this same bug on chrome + metamask when i try to change any subdomain properties. No error when updating domain..
<img width="1423" alt="Screenshot 2020-12-10 at 11 10 39" src="https://user-images.githubusercontent.com/4284362/101765287-04562200-3ad9-11eb-91d0-5100d66fa2c7.png">

**Comment by acegilz** [comment]
@ghost after chatting with the admin on discord, we discovered that due to a bug, subdomains are being created with the old resolver..

Go to the subdomain resolver, click set resolver, click "Use public resolver", save, and try again.

In my case it was using the public resolver 1, instead of 2

**Comment by makoto** [comment]
This is fixed at https://github.com/ensdomains/ens-app/pull/1027/files. It will now create with the latest public resolver and if your existing subdomain points to old one it suggests to migrate.
