### ISSUE TITLE
Tried to register...but?!

### ISSUE THREAD

**Issue by willywilly12345** [ensdomains/ens-app#996]
Why in the world the app doesn't shows the total price from the start? I need to guess? 

Also.., the count starts from 1 year, but it seems i can also enter 0.1 years... so i have chosen 0.1 with a total price of 0.001 which i paid. After verifying it asks for 9$ more... it doesn't seem fair. I really thought that i can register for 0.1 years with 2 transaction of 0.001.

**Comment by makoto** [comment]
We show the registration price upfront. Do you mean gasPrice?

**Comment by makoto** [comment]
`so i have chosen 0.1 with a total price of 0.001 which i paid. After verifying it asks for 9$ more... ` you pay our registration cost at step3. What you paid in step 1 is the gas price for requesting to register (which you have to do to prevent someone from frontrunning you). This is fairly similar to how you transer ERC20 tokens (first you send transaction to `approve` then send another one to `transfer`) to any defi smartcontract.

**Comment by willywilly12345** [comment]
The second price is gas price?

**Comment by makoto** [comment]
I am closing this as this is more of usage question. Feel free to jump into our discord channel https://discord.gg/AskZbFx
